export const vietnamAddresses = {
  "Thành phố Cần Thơ": [
    "Phường An Bình",
    "Phường Bình Thủy",
    "Phường Cái Khế",
    "Phường Cái Răng",
    "Phường Đại Thành",
    "Phường Hưng Phú",
    "Phường Khánh Hòa",
    "Phường Long Bình",
    "Phường Long Mỹ",
    "Phường Long Phú 1",
    "Phường Long Tuyền",
    "Phường Mỹ Quới",
    "Phường Mỹ Xuyên",
    "Phường Ngã Bảy",
    "Phường Ngã Năm",
    "Phường Ninh Kiều",
    "Phường Ô Môn",
    "Phường Phú Lợi",
    "Phường Phước Thới",
    "Phường Sóc Trăng",
    "Phường Tân An",
    "Phường Tân Lộc",
    "Phường Thới An Đông",
    "Phường Thới Long",
    "Phường Thốt Nốt",
    "Phường Thuận Hưng",
    "Phường Trung Nhứt",
    "Phường Vị Tân",
    "Phường Vị Thanh",
    "Phường Vĩnh Châu",
    "Phường Vĩnh Phước",
    "Xã  Đại Hải",
    "Xã  Phú Hữu",
    "Xã An Lạc Thôn",
    "Xã An Ninh",
    "Xã An Thạnh",
    "Xã Châu Thành",
    "Xã Cờ Đỏ",
    "Xã Cù Lao Dung",
    "Xã Đại Ngãi",
    "Xã Đông Hiệp",
    "Xã Đông Phước",
    "Xã Đông Thuận",
    "Xã Gia Hòa",
    "Xã Hiệp Hưng",
    "Xã Hồ Đắc Kiện",
    "Xã Hòa An",
    "Xã Hỏa Lựu",
    "Xã Hòa Tú",
    "Xã Kế Sách",
    "Xã Lai Hòa",
    "Xã Lâm Tân",
    "Xã Lịch Hội Thượng",
    "Xã Liêu Tú",
    "Xã Long Hưng",
    "Xã Long Phú",
    "Xã Lương Tâm",
    "Xã Mỹ Hương",
    "Xã Mỹ Phước",
    "Xã Mỹ Tú",
    "Xã Ngọc Tố",
    "Xã Nhơn Ái",
    "Xã Nhơn Mỹ",
    "Xã Nhu Gia",
    "Xã Phong Điền",
    "Xã Phong Nẫm",
    "Xã Phú Lộc",
    "Xã Phú Tâm",
    "Xã Phụng Hiệp",
    "Xã Phương Bình",
    "Xã Tài Văn",
    "Xã Tân Bình",
    "Xã Tân Hòa",
    "Xã Tân Long",
    "Xã Tân Phước Hưng",
    "Xã Tân Thạnh",
    "Xã Thạnh An",
    "Xã Thạnh Hòa",
    "Xã Thạnh Phú",
    "Xã Thạnh Quới",
    "Xã Thạnh Thới An",
    "Xã Thạnh Xuân",
    "Xã Thới An Hội",
    "Xã Thới Hưng",
    "Xã Thới Lai",
    "Xã Thuận Hòa",
    "Xã Trần Đề",
    "Xã Trung Hưng",
    "Xã Trường Khánh",
    "Xã Trường Long",
    "Xã Trường Long Tây",
    "Xã Trường Thành",
    "Xã Trường Xuân",
    "Xã Vị Thanh 1",
    "Xã Vị Thủy",
    "Xã Vĩnh Hải",
    "Xã Vĩnh Lợi",
    "Xã Vĩnh Thạnh",
    "Xã Vĩnh Thuận Đông",
    "Xã Vĩnh Trinh",
    "Xã Vĩnh Tường",
    "Xã Vĩnh Viễn",
    "Xã Xà Phiên",
  ],
  "Thành phố Đà Nẵng": [
    "Đặc khu Hoàng Sa",
    "Phường An Hải",
    "Phường An Khê",
    "Phường An Thắng",
    "Phường Bàn Thạch",
    "Phường Cẩm Lệ",
    "Phường Điện Bàn",
    "Phường Điện Bàn Bắc",
    "Phường Điện Bàn Đông",
    "Phường Hải Châu",
    "Phường Hải Vân",
    "Phường Hòa Cường",
    "Phường Hòa Khánh",
    "Phường Hòa Xuân",
    "Phường Hội An",
    "Phường Hội An Đông",
    "Phường Hội An Tây",
    "Phường Hương Trà",
    "Phường Liên Chiểu",
    "Phường Ngũ Hành Sơn",
    "Phường Quảng Phú",
    "Phường Sơn Trà",
    "Phường Tam Kỳ",
    "Phường Thanh Khê",
    "Xã Avương",
    "Xã Bà Nà",
    "Xã Bến Giằng",
    "Xã Bến Hiên",
    "Xã Chiên Đàn",
    "Xã Đắc Pring",
    "Xã Đại Lộc",
    "Xã Điện Bàn Tây",
    "Xã Đồng Dương",
    "Xã Đông Giang",
    "Xã Đức Phú",
    "Xã Duy Nghĩa",
    "Xã Duy Xuyên",
    "Xã Gò Nổi",
    "Xã Hà Nha",
    "Xã Hiệp Đức",
    "Xã Hòa Tiến",
    "Xã Hòa Vang",
    "Xã Hùng Sơn",
    "Xã Khâm Đức",
    "Xã La Dêê",
    "Xã La Êê",
    "Xã Lãnh Ngọc",
    "Xã Nam Giang",
    "Xã Nam Phước",
    "Xã Nam Trà My",
    "Xã Nông Sơn",
    "Xã Núi Thành",
    "Xã Phú Ninh",
    "Xã Phú Thuận",
    "Xã Phước Chánh",
    "Xã Phước Hiệp",
    "Xã Phước Năng",
    "Xã Phước Thành",
    "Xã Phước Trà",
    "Xã Quế Phước",
    "Xã Quế Sơn",
    "Xã Quế Sơn Trung",
    "Xã Sơn Cẩm Hà",
    "Xã Sông Kôn",
    "Xã Sông Vàng",
    "Xã Tam Anh",
    "Xã Tam Hải",
    "Xã Tam Mỹ",
    "Xã Tam Xuân",
    "Xã Tân Hiệp",
    "Xã Tây Giang",
    "Xã Tây Hồ",
    "Xã Thăng An",
    "Xã Thăng Bình",
    "Xã Thăng Điền",
    "Xã Thăng Phú",
    "Xã Thăng Trường",
    "Xã Thạnh Bình",
    "Xã Thạnh Mỹ",
    "Xã Thu Bồn",
    "Xã Thượng Đức",
    "Xã Tiên Phước",
    "Xã Trà Đốc",
    "Xã Trà Giáp",
    "Xã Trà Leng",
    "Xã Trà Liên",
    "Xã Trà Linh",
    "Xã Trà My",
    "Xã Trà Tân",
    "Xã Trà Tập",
    "Xã Trà Vân",
    "Xã Việt An",
    "Xã Vu Gia",
    "Xã Xuân Phú",
  ],
  "Thành phố Hà Nội": [
    "Phường Ba Đình",
    "Phường Bạch Mai",
    "Phường Bồ Đề",
    "Phường Cầu Giấy",
    "Phường Chương Mỹ",
    "Phường Cửa Nam",
    "Phường Đại Mỗ",
    "Phường Định Công",
    "Phường Đống Đa",
    "Phường Đông Ngạc",
    "Phường Dương Nội",
    "Phường Giảng Võ",
    "Phường Hà Đông",
    "Phường Hai Bà Trưng",
    "Phường Hoàn Kiếm",
    "Phường Hoàng Liệt",
    "Phường Hoàng Mai",
    "Phường Hồng Hà",
    "Phường Khương Đình",
    "Phường Kiến Hưng",
    "Phường Kim Liên",
    "Phường Láng",
    "Phường Lĩnh Nam",
    "Phường Long Biên",
    "Phường Nghĩa Đô",
    "Phường Ngọc Hà",
    "Phường Ô Chợ Dừa",
    "Phường Phú Diễn",
    "Phường Phú Lương",
    "Phường Phú Thượng",
    "Phường Phúc Lợi",
    "Phường Phương Liệt",
    "Phường Sơn Tây",
    "Phường Tây Hồ",
    "Phường Tây Mỗ",
    "Phường Tây Tựu",
    "Phường Thanh Liệt",
    "Phường Thanh Xuân",
    "Phường Thượng Cát",
    "Phường Từ Liêm",
    "Phường Tùng Thiện",
    "Phường Tương Mai",
    "Phường Văn Miếu - Quốc Tử Giám",
    "Phường Việt Hưng",
    "Phường Vĩnh Hưng",
    "Phường Vĩnh Tuy",
    "Phường Xuân Đỉnh",
    "Phường Xuân Phương",
    "Phường Yên Hòa",
    "Phường Yên Nghĩa",
    "Phường Yên Sở",
    "Xã An Khánh",
    "Xã Ba Vì",
    "Xã Bất Bạt",
    "Xã Bát Tràng",
    "Xã Bình Minh",
    "Xã Chương Dương",
    "Xã Chuyên Mỹ",
    "Xã Cổ Đô",
    "Xã Đa Phúc",
    "Xã Đại Thanh",
    "Xã Đại Xuyên",
    "Xã Dân Hòa",
    "Xã Đan Phượng",
    "Xã Đoài Phương",
    "Xã Đông Anh",
    "Xã Dương Hòa",
    "Xã Gia Lâm",
    "Xã Hạ Bằng",
    "Xã Hát Môn",
    "Xã Hòa Lạc",
    "Xã Hòa Phú",
    "Xã Hòa Xá",
    "Xã Hoài Đức",
    "Xã Hồng Sơn",
    "Xã Hồng Vân",
    "Xã Hưng Đạo",
    "Xã Hương Sơn",
    "Xã Kiều Phú",
    "Xã Kim Anh",
    "Xã Liên Minh",
    "Xã Mê Linh",
    "Xã Minh Châu",
    "Xã Mỹ Đức",
    "Xã Nam Phù",
    "Xã Ngọc Hồi",
    "Xã Nội Bài",
    "Xã Ô Diên",
    "Xã Phú Cát",
    "Xã Phù Đổng",
    "Xã Phú Nghĩa",
    "Xã Phú Xuyên",
    "Xã Phúc Lộc",
    "Xã Phúc Sơn",
    "Xã Phúc Thịnh",
    "Xã Phúc Thọ",
    "Xã Phượng Dực",
    "Xã Quảng Bị",
    "Xã Quang Minh",
    "Xã Quảng Oai",
    "Xã Quốc Oai",
    "Xã Sóc Sơn",
    "Xã Sơn Đồng",
    "Xã Suối Hai",
    "Xã Tam Hưng",
    "Xã Tây Phương",
    "Xã Thạch Thất",
    "Xã Thanh Oai",
    "Xã Thanh Trì",
    "Xã Thiên Lộc",
    "Xã Thư Lâm",
    "Xã Thuận An",
    "Xã Thượng Phúc",
    "Xã Thường Tín",
    "Xã Tiến Thắng",
    "Xã Trần Phú",
    "Xã Trung Giã",
    "Xã Ứng Hòa",
    "Xã Ứng Thiên",
    "Xã Vân Đình",
    "Xã Vật Lại",
    "Xã Vĩnh Thanh",
    "Xã Xuân Mai",
    "Xã Yên Bài",
    "Xã Yên Lãng",
    "Xã Yên Xuân",
  ],
  "Thành phố Hải Phòng": [
    "Đặc khu Bạch Long Vĩ",
    "Đặc khu Cát Hải",
    "Phường Ái Quốc",
    "Phường An Biên",
    "Phường An Dương",
    "Phường An Hải",
    "Phường An Phong",
    "Phường Bắc An Phụ",
    "Phường Bạch Đằng",
    "Phường Chí Linh",
    "Phường Chu Văn An",
    "Phường Đồ Sơn",
    "Phường Đông Hải",
    "Phường Dương Kinh",
    "Phường Gia Viên",
    "Phường Hải An",
    "Phường Hải Dương",
    "Phường Hòa Bình",
    "Phường Hồng An",
    "Phường Hồng Bàng",
    "Phường Hưng Đạo",
    "Phường Kiến An",
    "Phường Kinh Môn",
    "Phường Lê Chân",
    "Phường Lê Đại Hành",
    "Phường Lê Ích Mộc",
    "Phường Lê Thanh Nghị",
    "Phường Lưu Kiếm",
    "Phường Nam Đồ Sơn",
    "Phường Nam Đồng",
    "Phường Nam Triệu",
    "Phường Ngô Quyền",
    "Phường Nguyễn Đại Năng",
    "Phường Nguyễn Trãi",
    "Phường Nhị Chiểu",
    "Phường Phạm Sư Mạnh",
    "Phường Phù Liễn",
    "Phường Tân Hưng",
    "Phường Thạch Khôi",
    "Phường Thành Đông",
    "Phường Thiên Hương",
    "Phường Thủy Nguyên",
    "Phường Trần Hưng Đạo",
    "Phường Trần Liễu",
    "Phường Trần Nhân Tông",
    "Phường Tứ Minh",
    "Phường Việt Hòa",
    "Xã An Hưng",
    "Xã An Khánh",
    "Xã An Lão",
    "Xã An Phú",
    "Xã An Quang",
    "Xã An Thành",
    "Xã An Trường",
    "Xã Bắc Thanh Miện",
    "Xã Bình Giang",
    "Xã Cẩm Giang",
    "Xã Cẩm Giàng",
    "Xã Chấn Hưng",
    "Xã Chí Minh",
    "Xã Đại Sơn",
    "Xã Đường An",
    "Xã Gia Lộc",
    "Xã Gia Phúc",
    "Xã Hà Bắc",
    "Xã Hà Đông",
    "Xã Hà Nam",
    "Xã Hà Tây",
    "Xã Hải Hưng",
    "Xã Hồng Châu",
    "Xã Hợp Tiến",
    "Xã Hùng Thắng",
    "Xã Kẻ Sặt",
    "Xã Khúc Thừa Dụ",
    "Xã Kiến Hải",
    "Xã Kiến Hưng",
    "Xã Kiến Minh",
    "Xã Kiến Thụy",
    "Xã Kim Thành",
    "Xã Lạc Phượng",
    "Xã Lai Khê",
    "Xã Mao Điền",
    "Xã Nam An Phụ",
    "Xã Nam Sách",
    "Xã Nam Thanh Miện",
    "Xã Nghi Dương",
    "Xã Nguyễn Bỉnh Khiêm",
    "Xã Nguyên Giáp",
    "Xã Nguyễn Lương Bằng",
    "Xã Ninh Giang",
    "Xã Phú Thái",
    "Xã Quyết Thắng",
    "Xã Tân An",
    "Xã Tân Kỳ",
    "Xã Tân Minh",
    "Xã Thái Tân",
    "Xã Thanh Hà",
    "Xã Thanh Miện",
    "Xã Thượng Hồng",
    "Xã Tiên Lãng",
    "Xã Tiên Minh",
    "Xã Trần Phú",
    "Xã Trường Tân",
    "Xã Tứ Kỳ",
    "Xã Tuệ Tĩnh",
    "Xã Việt Khê",
    "Xã Vĩnh Am",
    "Xã Vĩnh Bảo",
    "Xã Vĩnh Hải",
    "Xã Vĩnh Hòa",
    "Xã Vĩnh Lại",
    "Xã Vĩnh Thịnh",
    "Xã Vĩnh Thuận",
    "Xã Yết Kiêu",
  ],
  "Thành phố Hồ Chí Minh": [
    "Đặc khu Côn Đảo",
    "Phường  An Nhơn",
    "Phường  Rạch Dừa",
    "Phường An Đông",
    "Phường An Hội Đông",
    "Phường An Hội Tây",
    "Phường An Khánh",
    "Phường An Lạc",
    "Phường An Phú",
    "Phường An Phú Đông",
    "Phường Bà Rịa",
    "Phường Bàn Cờ",
    "Phường Bảy Hiền",
    "Phường Bến Cát",
    "Phường Bến Thành",
    "Phường Bình Cơ",
    "Phường Bình Đông",
    "Phường Bình Dương",
    "Phường Bình Hòa",
    "Phường Bình Hưng Hòa",
    "Phường Bình Lợi Trung",
    "Phường Bình Phú",
    "Phường Bình Quới",
    "Phường Bình Tân",
    "Phường Bình Tây",
    "Phường Bình Thạnh",
    "Phường Bình Thới",
    "Phường Bình Tiên",
    "Phường Bình Trị Đông",
    "Phường Bình Trưng",
    "Phường Cát Lái",
    "Phường Cầu Kiệu",
    "Phường Cầu Ông Lãnh",
    "Phường Chánh Hiệp",
    "Phường Chánh Hưng",
    "Phường Chánh Phú Hòa",
    "Phường Chợ Lớn",
    "Phường Chợ Quán",
    "Phường Dĩ An",
    "Phường Diên Hồng",
    "Phường Đông Hòa",
    "Phường Đông Hưng Thuận",
    "Phường Đức Nhuận",
    "Phường Gia Định",
    "Phường Gò Vấp",
    "Phường Hạnh Thông",
    "Phường Hiệp Bình",
    "Phường Hòa Bình",
    "Phường Hòa Hưng",
    "Phường Hòa Lợi",
    "Phường Khánh Hội",
    "Phường Lái Thiêu",
    "Phường Linh Xuân",
    "Phường Long Bình",
    "Phường Long Hương",
    "Phường Long Nguyên",
    "Phường Long Phước",
    "Phường Long Trường",
    "Phường Minh Phụng",
    "Phường Nhiêu Lộc",
    "Phường Phú An",
    "Phường Phú Định",
    "Phường Phú Lâm",
    "Phường Phú Lợi",
    "Phường Phú Mỹ",
    "Phường Phú Nhuận",
    "Phường Phú Thạnh",
    "Phường Phú Thọ",
    "Phường Phú Thọ Hòa",
    "Phường Phú Thuận",
    "Phường Phước Long",
    "Phường Phước Thắng",
    "Phường Sài Gòn",
    "Phường Tam Bình",
    "Phường Tam Long",
    "Phường Tam Thắng",
    "Phường Tân Bình",
    "Phường Tân Định",
    "Phường Tân Đông Hiệp",
    "Phường Tân Hải",
    "Phường Tân Hiệp",
    "Phường Tân Hòa",
    "Phường Tân Hưng",
    "Phường Tân Khánh",
    "Phường Tân Mỹ",
    "Phường Tân Phú",
    "Phường Tân Phước",
    "Phường Tân Sơn",
    "Phường Tân Sơn Hòa",
    "Phường Tân Sơn Nhất",
    "Phường Tân Sơn Nhì",
    "Phường Tân Tạo",
    "Phường Tân Thành",
    "Phường Tân Thới Hiệp",
    "Phường Tân Thuận",
    "Phường Tân Uyên",
    "Phường Tăng Nhơn Phú",
    "Phường Tây Nam",
    "Phường Tây Thạnh",
    "Phường Thạnh Mỹ Tây",
    "Phường Thới An",
    "Phường Thới Hòa",
    "Phường Thông Tây Hội",
    "Phường Thủ Dầu Một",
    "Phường Thủ Đức",
    "Phường Thuận An",
    "Phường Thuận Giao",
    "Phường Trung Mỹ Tây",
    "Phường Vĩnh Hội",
    "Phường Vĩnh Tân",
    "Phường Vũng Tàu",
    "Phường Vườn Lài",
    "Phường Xóm Chiếu",
    "Phường Xuân Hòa",
    "Xã An Long",
    "Xã An Nhơn Tây",
    "Xã An Thới Đông",
    "Xã Bà Điểm",
    "Xã Bắc Tân Uyên",
    "Xã Bàu Bàng",
    "Xã Bàu Lâm",
    "Xã Bình Chánh",
    "Xã Bình Châu",
    "Xã Bình Giã",
    "Xã Bình Hưng",
    "Xã Bình Khánh",
    "Xã Bình Lợi",
    "Xã Bình Mỹ",
    "Xã Cần Giờ",
    "Xã Châu Đức",
    "Xã Châu Pha",
    "Xã Củ Chi",
    "Xã Đất Đỏ",
    "Xã Dầu Tiếng",
    "Xã Đông Thạnh",
    "Xã Hiệp Phước",
    "Xã Hồ Tràm",
    "Xã Hòa Hiệp",
    "Xã Hòa Hội",
    "Xã Hóc Môn",
    "Xã Hưng Long",
    "Xã Kim Long",
    "Xã Long Điền",
    "Xã Long Hải",
    "Xã Long Hòa",
    "Xã Long Sơn",
    "Xã Minh Thạnh",
    "Xã Ngãi Giao",
    "Xã Nghĩa Thành",
    "Xã Nhà Bè",
    "Xã Nhuận Đức",
    "Xã Phú Giáo",
    "Xã Phú Hòa Đông",
    "Xã Phước Hải",
    "Xã Phước Hòa",
    "Xã Phước Thành",
    "Xã Tân An Hội",
    "Xã Tân Nhựt",
    "Xã Tân Vĩnh Lộc",
    "Xã Thái Mỹ",
    "Xã Thanh An",
    "Xã Thạnh An",
    "Xã Thường Tân",
    "Xã Trừ Văn Thố",
    "Xã Vĩnh Lộc",
    "Xã Xuân Sơn",
    "Xã Xuân Thới Sơn",
    "Xã Xuyên Mộc",
  ],
  "Thành phố Huế": [
    "Phường An Cựu",
    "Phường Dương Nỗ",
    "Phường Hóa Châu",
    "Phường Hương An",
    "Phường Hương Thủy",
    "Phường Hương Trà",
    "Phường Kim Long",
    "Phường Kim Trà",
    "Phường Mỹ Thượng",
    "Phường Phong Điền",
    "Phường Phong Dinh",
    "Phường Phong Phú",
    "Phường Phong Quảng",
    "Phường Phong Thái",
    "Phường Phú Bài",
    "Phường Phú Xuân",
    "Phường Thanh Thủy",
    "Phường Thuận An",
    "Phường Thuận Hóa",
    "Phường Thủy Xuân",
    "Phường Vỹ Dạ",
    "Xã A Lưới 1",
    "Xã A Lưới 2",
    "Xã A Lưới 3",
    "Xã A Lưới 4",
    "Xã A Lưới 5",
    "Xã Bình Điền",
    "Xã Chân Mây - Lăng Cô",
    "Xã Đan Điền",
    "Xã Hưng Lộc",
    "Xã Khe Tre",
    "Xã Lộc An",
    "Xã Long Quảng",
    "Xã Nam Đông",
    "Xã Phú Hồ",
    "Xã Phú Lộc",
    "Xã Phú Vang",
    "Xã Phú Vinh",
    "Xã Quảng Điền",
    "Xã Vinh Lộc",
  ],
  "Tỉnh An Giang": [
    "Đặc khu Kiên Hải",
    "Đặc khu Phú Quốc",
    "Đặc khu Thổ Châu",
    "Phường Bình Đức",
    "Phường Châu Đốc",
    "Phường Chi Lăng",
    "Phường Hà Tiên",
    "Phường Long Phú",
    "Phường Long Xuyên",
    "Phường Mỹ Thới",
    "Phường Rạch Giá",
    "Phường Tân Châu",
    "Phường Thới Sơn",
    "Phường Tịnh Biên",
    "Phường Tô Châu",
    "Phường Vĩnh Tế",
    "Phường Vĩnh Thông",
    "Xã An Biên",
    "Xã An Châu",
    "Xã An Cư",
    "Xã An Minh",
    "Xã An Phú",
    "Xã Ba Chúc",
    "Xã Bình An",
    "Xã Bình Giang",
    "Xã Bình Hòa",
    "Xã Bình Mỹ",
    "Xã Bình Sơn",
    "Xã Bình Thạnh Đông",
    "Xã Cần Đăng",
    "Xã Châu Phong",
    "Xã Châu Phú",
    "Xã Châu Thành",
    "Xã Chợ Mới",
    "Xã Chợ Vàm",
    "Xã Cô Tô",
    "Xã Cù Lao Giêng",
    "Xã Định Hòa",
    "Xã Định Mỹ",
    "Xã Đông Hòa",
    "Xã Đông Hưng",
    "Xã Đông Thái",
    "Xã Giang Thành",
    "Xã Giồng Riềng",
    "Xã Gò Quao",
    "Xã Hòa Điền",
    "Xã Hòa Hưng",
    "Xã Hòa Lạc",
    "Xã Hòa Thuận",
    "Xã Hội An",
    "Xã Hòn Đất",
    "Xã Hòn Nghệ",
    "Xã Khánh Bình",
    "Xã Kiên Lương",
    "Xã Long Điền",
    "Xã Long Kiến",
    "Xã Long Thạnh",
    "Xã Mỹ Đức",
    "Xã Mỹ Hòa Hưng",
    "Xã Mỹ Thuận",
    "Xã Ngọc Chúc",
    "Xã Nhơn Hội",
    "Xã Nhơn Mỹ",
    "Xã Núi Cấm",
    "Xã Ô Lâm",
    "Xã Óc Eo",
    "Xã Phú An",
    "Xã Phú Hòa",
    "Xã Phú Hữu",
    "Xã Phú Lâm",
    "Xã Phú Tân",
    "Xã Sơn Hải",
    "Xã Sơn Kiên",
    "Xã Tân An",
    "Xã Tân Hiệp",
    "Xã Tân Hội",
    "Xã Tân Thạnh",
    "Xã Tây Phú",
    "Xã Tây Yên",
    "Xã Thạnh Đông",
    "Xã Thạnh Hưng",
    "Xã Thạnh Lộc",
    "Xã Thạnh Mỹ Tây",
    "Xã Thoại Sơn",
    "Xã Tiên Hải",
    "Xã Tri Tôn",
    "Xã U Minh Thượng",
    "Xã Vân Khánh",
    "Xã Vĩnh An",
    "Xã Vĩnh Bình",
    "Xã Vĩnh Điều",
    "Xã Vĩnh Gia",
    "Xã Vĩnh Hanh",
    "Xã Vĩnh Hậu",
    "Xã Vĩnh Hòa",
    "Xã Vĩnh Hòa Hưng",
    "Xã Vĩnh Phong",
    "Xã Vĩnh Thạnh Trung",
    "Xã Vĩnh Thuận",
    "Xã Vĩnh Trạch",
    "Xã Vĩnh Tuy",
    "Xã Vĩnh Xương",
  ],
  "Tỉnh Bắc Ninh": [
    "Phường Bắc Giang",
    "Phường Bồng Lai",
    "Phường Cảnh Thụy",
    "Phường Chũ",
    "Phường Đa Mai",
    "Phường Đào Viên",
    "Phường Đồng Nguyên",
    "Phường Hạp Lĩnh",
    "Phường Kinh Bắc",
    "Phường Mão Điền",
    "Phường Nam Sơn",
    "Phường Nếnh",
    "Phường Nhân Hòa",
    "Phường Ninh Xá",
    "Phường Phù Khê",
    "Phường Phương Liễu",
    "Phường Phượng Sơn",
    "Phường Quế Võ",
    "Phường Song Liễu",
    "Phường Tam Sơn",
    "Phường Tân An",
    "Phường Tân Tiến",
    "Phường Thuận Thành",
    "Phường Tiền Phong",
    "Phường Trạm Lộ",
    "Phường Trí Quả",
    "Phường Tự Lạn",
    "Phường Từ Sơn",
    "Phường Vân Hà",
    "Phường Việt Yên",
    "Phường Võ Cường",
    "Phường Vũ Ninh",
    "Phường Yên Dũng",
    "Xã An Lạc",
    "Xã Bắc Lũng",
    "Xã Bảo Đài",
    "Xã Biển Động",
    "Xã Biên Sơn",
    "Xã Bố Hạ",
    "Xã Cẩm Lý",
    "Xã Cao Đức",
    "Xã Chi Lăng",
    "Xã Đại Đồng",
    "Xã Đại Lai",
    "Xã Đại Sơn",
    "Xã Đèo Gia",
    "Xã Đông Cứu",
    "Xã Đồng Kỳ",
    "Xã Đông Phú",
    "Xã Đồng Việt",
    "Xã Dương Hưu",
    "Xã Gia Bình",
    "Xã Hiệp Hòa",
    "Xã Hoàng Vân",
    "Xã Hợp Thịnh",
    "Xã Kép",
    "Xã Kiên Lao",
    "Xã Lâm Thao",
    "Xã Lạng Giang",
    "Xã Liên Bão",
    "Xã Lục Nam",
    "Xã Lục Ngạn",
    "Xã Lục Sơn",
    "Xã Lương Tài",
    "Xã Mỹ Thái",
    "Xã Nam Dương",
    "Xã Nghĩa Phương",
    "Xã Ngọc Thiện",
    "Xã Nhã Nam",
    "Xã Nhân Thắng",
    "Xã Phật Tích",
    "Xã Phù Lãng",
    "Xã Phúc Hòa",
    "Xã Quang Trung",
    "Xã Sa Lý",
    "Xã Sơn Động",
    "Xã Sơn Hải",
    "Xã Tam Đa",
    "Xã Tam Giang",
    "Xã Tam Tiến",
    "Xã Tân Chi",
    "Xã Tân Dĩnh",
    "Xã Tân Sơn",
    "Xã Tân Yên",
    "Xã Tây Yên Tử",
    "Xã Tiên Du",
    "Xã Tiên Lục",
    "Xã Trung Chính",
    "Xã Trung Kênh",
    "Xã Trường Sơn",
    "Xã Tuấn Đạo",
    "Xã Văn Môn",
    "Xã Vân Sơn",
    "Xã Xuân Cẩm",
    "Xã Xuân Lương",
    "Xã Yên Định",
    "Xã Yên Phong",
    "Xã Yên Thế",
    "Xã Yên Trung",
  ],
  "Tỉnh Cà Mau": [
    "Phường An Xuyên",
    "Phường Bạc Liêu",
    "Phường Giá Rai",
    "Phường Hiệp Thành",
    "Phường Hòa Thành",
    "Phường Láng Tròn",
    "Phường Lý Văn Lâm",
    "Phường Tân Thành",
    "Phường Vĩnh Trạch",
    "Xã An Trạch",
    "Xã Biển Bạch",
    "Xã Cái Đôi Vàm",
    "Xã Cái Nước",
    "Xã Châu Thới",
    "Xã Đá Bạc",
    "Xã Đầm Dơi",
    "Xã Đất Mới",
    "Xã Đất Mũi",
    "Xã Định Thành",
    "Xã Đông Hải",
    "Xã Gành Hào",
    "Xã Hồ Thị Kỷ",
    "Xã Hòa Bình",
    "Xã Hồng Dân",
    "Xã Hưng Hội",
    "Xã Hưng Mỹ",
    "Xã Khánh An",
    "Xã Khánh Bình",
    "Xã Khánh Hưng",
    "Xã Khánh Lâm",
    "Xã Long Điền",
    "Xã Lương Thế Trân",
    "Xã Năm Căn",
    "Xã Nguyễn Phích",
    "Xã Nguyễn Việt Khái",
    "Xã Ninh Quới",
    "Xã Ninh Thạnh Lợi",
    "Xã Phan Ngọc Hiển",
    "Xã Phong Hiệp",
    "Xã Phong Thạnh",
    "Xã Phú Mỹ",
    "Xã Phú Tân",
    "Xã Phước Long",
    "Xã Quách Phẩm",
    "Xã Sông Đốc",
    "Xã Tạ An Khương",
    "Xã Tam Giang",
    "Xã Tân Ân",
    "Xã Tân Hưng",
    "Xã Tân Lộc",
    "Xã Tân Thuận",
    "Xã Tân Tiến",
    "Xã Thanh Tùng",
    "Xã Thới Bình",
    "Xã Trần Phán",
    "Xã Trần Văn Thời",
    "Xã Trí Phải",
    "Xã U Minh",
    "Xã Vĩnh Hậu",
    "Xã Vĩnh Lộc",
    "Xã Vĩnh Lợi",
    "Xã Vĩnh Mỹ",
    "Xã Vĩnh Phước",
    "Xã Vĩnh Thanh",
  ],
  "Tỉnh Cao Bằng": [
    "Phường Nùng Trí Cao",
    "Phường Tân Giang",
    "Phường Thục Phán",
    "Xã Bạch Đằng",
    "Xã Bảo Lạc",
    "Xã Bảo Lâm",
    "Xã Bế Văn Đàn",
    "Xã Ca Thành",
    "Xã Cần Yên",
    "Xã Canh Tân",
    "Xã Cô Ba",
    "Xã Cốc Pàng",
    "Xã Đàm Thủy",
    "Xã Đình Phong",
    "Xã Đoài Dương",
    "Xã Độc Lập",
    "Xã Đông Khê",
    "Xã Đức Long",
    "Xã Hạ Lang",
    "Xã Hà Quảng",
    "Xã Hạnh Phúc",
    "Xã Hòa An",
    "Xã Hưng Đạo",
    "Xã Huy Giáp",
    "Xã Khánh Xuân",
    "Xã Kim Đồng",
    "Xã Lũng Nặm",
    "Xã Lý Bôn",
    "Xã Lý Quốc",
    "Xã Minh Khai",
    "Xã Minh Tâm",
    "Xã Nam Quang",
    "Xã Nam Tuấn",
    "Xã Nguyên Bình",
    "Xã Nguyễn Huệ",
    "Xã Phan Thanh",
    "Xã Phục Hòa",
    "Xã Quang Hán",
    "Xã Quảng Lâm",
    "Xã Quang Long",
    "Xã Quang Trung",
    "Xã Quảng Uyên",
    "Xã Sơn Lộ",
    "Xã Tam Kim",
    "Xã Thạch An",
    "Xã Thành Công",
    "Xã Thanh Long",
    "Xã Thông Nông",
    "Xã Tĩnh Túc",
    "Xã Tổng Cọt",
    "Xã Trà Lĩnh",
    "Xã Trùng Khánh",
    "Xã Trường Hà",
    "Xã Vinh Quý",
    "Xã Xuân Trường",
    "Xã Yên Thổ",
  ],
  "Tỉnh Đắk Lắk": [
    "Phường Bình Kiến",
    "Phường Buôn Hồ",
    "Phường Buôn Ma Thuột",
    "Phường Cư Bao",
    "Phường Đông Hòa",
    "Phường Ea Kao",
    "Phường Hòa Hiệp",
    "Phường Phú Yên",
    "Phường Sông Cầu",
    "Phường Tân An",
    "Phường Tân Lập",
    "Phường Thành Nhất",
    "Phường Tuy Hòa",
    "Phường Xuân Đài",
    "Xã Buôn Đôn",
    "Xã Cư M’gar",
    "Xã Cư M’ta",
    "Xã Cư Pơng",
    "Xã Cư Prao",
    "Xã Cư Pui",
    "Xã Cư Yang",
    "Xã Cuôr Đăng",
    "Xã Đắk Liêng",
    "Xã Đắk Phơi",
    "Xã Dang Kang",
    "Xã Dliê Ya",
    "Xã Đồng Xuân",
    "Xã Dray Bhăng",
    "Xã Đức Bình",
    "Xã Dur Kmăl",
    "Xã Ea Bá",
    "Xã Ea Bung",
    "Xã Ea Drăng",
    "Xã Ea Drông",
    "Xã Ea H’Leo",
    "Xã Ea Hiao",
    "Xã Ea Kar",
    "Xã Ea Khăl",
    "Xã Ea Kiết",
    "Xã Ea Kly",
    "Xã Ea Knốp",
    "Xã Ea Knuếc",
    "Xã Ea Ktur",
    "Xã Ea Ly",
    "Xã Ea M’Droh",
    "Xã Ea Na",
    "Xã Ea Ning",
    "Xã Ea Nuôl",
    "Xã Ea Ô",
    "Xã Ea Păl",
    "Xã Ea Phê",
    "Xã Ea Riêng",
    "Xã Ea Rốk",
    "Xã Ea Súp",
    "Xã Ea Trang",
    "Xã Ea Tul",
    "Xã Ea Wer",
    "Xã Ea Wy",
    "Xã Hòa Mỹ",
    "Xã Hòa Phú",
    "Xã Hòa Sơn",
    "Xã Hòa Thịnh",
    "Xã Hòa Xuân",
    "Xã Ia Lốp",
    "Xã Ia Rvê",
    "Xã Krông Á",
    "Xã Krông Ana",
    "Xã Krông Bông",
    "Xã Krông Búk",
    "Xã Krông Năng",
    "Xã Krông Nô",
    "Xã Krông Pắc",
    "Xã Liên Sơn Lắk",
    "Xã M’Drắk",
    "Xã Nam Ka",
    "Xã Ô Loan",
    "Xã Phú Hòa 1",
    "Xã Phú Hòa 2",
    "Xã Phú Mỡ",
    "Xã Phú Xuân",
    "Xã Pơng Drang",
    "Xã Quảng Phú",
    "Xã Sơn Hòa",
    "Xã Sơn Thành",
    "Xã Sông Hinh",
    "Xã Suối Trai",
    "Xã Tam Giang",
    "Xã Tân Tiến",
    "Xã Tây Hòa",
    "Xã Tây Sơn",
    "Xã Tuy An Bắc",
    "Xã Tuy An Đông",
    "Xã Tuy An Nam",
    "Xã Tuy An Tây",
    "Xã Vân Hòa",
    "Xã Vụ Bổn",
    "Xã Xuân Cảnh",
    "Xã Xuân Lãnh",
    "Xã Xuân Lộc",
    "Xã Xuân Phước",
    "Xã Xuân Thọ",
    "Xã Yang Mao",
  ],
  "Tỉnh Điện Biên": [
    "Phường Điện Biên Phủ",
    "Phường Mường Lay",
    "Phường Mường Thanh",
    "Xã Búng Lao",
    "Xã Chà Tở",
    "Xã Chiềng Sinh",
    "Xã Mường Ảng",
    "Xã Mường Chà",
    "Xã Mường Lạn",
    "Xã Mường Luân",
    "Xã Mường Mùn",
    "Xã Mường Nhà",
    "Xã Mường Nhé",
    "Xã Mường Phăng",
    "Xã Mường Pồn",
    "Xã Mường Toong",
    "Xã Mường Tùng",
    "Xã Nà Bủng",
    "Xã Nà Hỳ",
    "Xã Na Sang",
    "Xã Na Son",
    "Xã Nà Tấu",
    "Xã Nậm Kè",
    "Xã Nậm Nèn",
    "Xã Núa Ngam",
    "Xã Pa Ham",
    "Xã Phình Giàng",
    "Xã Pu Nhi",
    "Xã Pú Nhung",
    "Xã Quài Tở",
    "Xã Quảng Lâm",
    "Xã Sam Mứn",
    "Xã Sáng Nhè",
    "Xã Si Pa Phìn",
    "Xã Sín Chải",
    "Xã Sín Thầu",
    "Xã Sính Phình",
    "Xã Thanh An",
    "Xã Thanh Nưa",
    "Xã Thanh Yên",
    "Xã Tìa Dình",
    "Xã Tủa Chùa",
    "Xã Tủa Thàng",
    "Xã Tuần Giáo",
    "Xã Xa Dung",
  ],
  "Tỉnh Đồng Nai": [
    "Phường An Lộc",
    "Phường Bảo Vinh",
    "Phường Biên Hòa",
    "Phường Bình Lộc",
    "Phường Bình Long",
    "Phường Bình Phước",
    "Phường Chơn Thành",
    "Phường Đồng Xoài",
    "Phường Hàng Gòn",
    "Phường Hố Nai",
    "Phường Long Bình",
    "Phường Long Hưng",
    "Phường Long Khánh",
    "Phường Minh Hưng",
    "Phường Phước Bình",
    "Phường Phước Long",
    "Phường Phước Tân",
    "Phường Tam Hiệp",
    "Phường Tam Phước",
    "Phường Tân Triều",
    "Phường Trấn Biên",
    "Phường Trảng Dài",
    "Phường Xuân Lập",
    "Xã An Phước",
    "Xã An Viễn",
    "Xã Bàu Hàm",
    "Xã Bình An",
    "Xã Bình Minh",
    "Xã Bình Tân",
    "Xã Bom Bo",
    "Xã Bù Đăng",
    "Xã Bù Gia Mập",
    "Xã Cẩm Mỹ",
    "Xã Đa Kia",
    "Xã Đại Phước",
    "Xã Đak Lua",
    "Xã Đak Nhau",
    "Xã Đăk Ơ",
    "Xã Dầu Giây",
    "Xã Định Quán",
    "Xã Đồng Phú",
    "Xã Đồng Tâm",
    "Xã Gia Kiệm",
    "Xã Hưng Phước",
    "Xã Hưng Thịnh",
    "Xã La Ngà",
    "Xã Lộc Hưng",
    "Xã Lộc Ninh",
    "Xã Lộc Quang",
    "Xã Lộc Tấn",
    "Xã Lộc Thành",
    "Xã Lộc Thạnh",
    "Xã Long Hà",
    "Xã Long Phước",
    "Xã Long Thành",
    "Xã Minh Đức",
    "Xã Nam Cát Tiên",
    "Xã Nghĩa Trung",
    "Xã Nha Bích",
    "Xã Nhơn Trạch",
    "Xã Phú Hòa",
    "Xã Phú Lâm",
    "Xã Phú Lý",
    "Xã Phú Nghĩa",
    "Xã Phú Riềng",
    "Xã Phú Trung",
    "Xã Phú Vinh",
    "Xã Phước An",
    "Xã Phước Sơn",
    "Xã Phước Thái",
    "Xã Sông Ray",
    "Xã Tà Lài",
    "Xã Tân An",
    "Xã Tân Hưng",
    "Xã Tân Khai",
    "Xã Tân Lợi",
    "Xã Tân Phú",
    "Xã Tân Quan",
    "Xã Tân Tiến",
    "Xã Thanh Sơn",
    "Xã Thiện Hưng",
    "Xã Thọ Sơn",
    "Xã Thống Nhất",
    "Xã Thuận Lợi",
    "Xã Trảng Bom",
    "Xã Trị An",
    "Xã Xuân Bắc",
    "Xã Xuân Định",
    "Xã Xuân Đông",
    "Xã Xuân Đường",
    "Xã Xuân Hòa",
    "Xã Xuân Lộc",
    "Xã Xuân Phú",
    "Xã Xuân Quế",
    "Xã Xuân Thành",
  ],
  "Tỉnh Đồng Tháp": [
    "Phường An Bình",
    "Phường Bình Xuân",
    "Phường Cai Lậy",
    "Phường Cao Lãnh",
    "Phường Đạo Thạnh",
    "Phường Gò Công",
    "Phường Hồng Ngự",
    "Phường Long Thuận",
    "Phường Mỹ Ngãi",
    "Phường Mỹ Phong",
    "Phường Mỹ Phước Tây",
    "Phường Mỹ Tho",
    "Phường Mỹ Trà",
    "Phường Nhị Quý",
    "Phường Sa Đéc",
    "Phường Sơn Qui",
    "Phường Thanh Hòa",
    "Phường Thới Sơn",
    "Phường Thường Lạc",
    "Phường Trung An",
    "Xã An Hòa",
    "Xã An Hữu",
    "Xã An Long",
    "Xã An Phước",
    "Xã An Thạnh Thủy",
    "Xã Ba Sao",
    "Xã Bình Hàng Trung",
    "Xã Bình Ninh",
    "Xã Bình Phú",
    "Xã Bình Thành",
    "Xã Bình Trưng",
    "Xã Cái Bè",
    "Xã Châu Thành",
    "Xã Chợ Gạo",
    "Xã Đốc Binh Kiều",
    "Xã Đồng Sơn",
    "Xã Gia Thuận",
    "Xã Gò Công Đông",
    "Xã Hậu Mỹ",
    "Xã Hiệp Đức",
    "Xã Hòa Long",
    "Xã Hội Cư",
    "Xã Hưng Thạnh",
    "Xã Kim Sơn",
    "Xã Lai Vung",
    "Xã Lấp Vò",
    "Xã Long Bình",
    "Xã Long Định",
    "Xã Long Hưng",
    "Xã Long Khánh",
    "Xã Long Phú Thuận",
    "Xã Long Tiên",
    "Xã Lương Hòa Lạc",
    "Xã Mỹ An Hưng",
    "Xã Mỹ Đức Tây",
    "Xã Mỹ Hiệp",
    "Xã Mỹ Lợi",
    "Xã Mỹ Quí",
    "Xã Mỹ Thành",
    "Xã Mỹ Thiện",
    "Xã Mỹ Thọ",
    "Xã Mỹ Tịnh An",
    "Xã Ngũ Hiệp",
    "Xã Phong Hòa",
    "Xã Phong Mỹ",
    "Xã Phú Cường",
    "Xã Phú Hựu",
    "Xã Phú Thành",
    "Xã Phú Thọ",
    "Xã Phương Thịnh",
    "Xã Tam Nông",
    "Xã Tân Điền",
    "Xã Tân Đông",
    "Xã Tân Dương",
    "Xã Tân Hộ Cơ",
    "Xã Tân Hòa",
    "Xã Tân Hồng",
    "Xã Tân Hương",
    "Xã Tân Khánh Trung",
    "Xã Tân Long",
    "Xã Tân Nhuận Đông",
    "Xã Tân Phú",
    "Xã Tân Phú Đông",
    "Xã Tân Phú Trung",
    "Xã Tân Phước 1",
    "Xã Tân Phước 2",
    "Xã Tân Phước 3",
    "Xã Tân Thành",
    "Xã Tân Thạnh",
    "Xã Tân Thới",
    "Xã Tân Thuận Bình",
    "Xã Thanh Bình",
    "Xã Thanh Hưng",
    "Xã Thanh Mỹ",
    "Xã Thạnh Phú",
    "Xã Tháp Mười",
    "Xã Thường Phước",
    "Xã Tràm Chim",
    "Xã Trường Xuân",
    "Xã Vĩnh Bình",
    "Xã Vĩnh Hựu",
    "Xã Vĩnh Kim",
  ],
  "Tỉnh Gia Lai": [
    "Phường An Bình",
    "Phường An Khê",
    "Phường An Nhơn",
    "Phường An Nhơn Bắc",
    "Phường An Nhơn Đông",
    "Phường An Nhơn Nam",
    "Phường An Phú",
    "Phường Ayun Pa",
    "Phường Bình Định",
    "Phường Bồng Sơn",
    "Phường Diên Hồng",
    "Phường Hoài Nhơn",
    "Phường Hoài Nhơn Bắc",
    "Phường Hoài Nhơn Đông",
    "Phường Hoài Nhơn Nam",
    "Phường Hoài Nhơn Tây",
    "Phường Hội Phú",
    "Phường Pleiku",
    "Phường Quy Nhơn",
    "Phường Quy Nhơn Bắc",
    "Phường Quy Nhơn Đông",
    "Phường Quy Nhơn Nam",
    "Phường Quy Nhơn Tây",
    "Phường Tam Quan",
    "Phường Thống Nhất",
    "Xã Al Bá",
    "Xã Ân Hảo",
    "Xã An Hòa",
    "Xã An Lão",
    "Xã An Lương",
    "Xã An Nhơn Tây",
    "Xã An Toàn",
    "Xã Ân Tường",
    "Xã An Vinh",
    "Xã Ayun",
    "Xã Bàu Cạn",
    "Xã Biển Hồ",
    "Xã Bình An",
    "Xã Bình Dương",
    "Xã Bình Hiệp",
    "Xã Bình Khê",
    "Xã Bình Phú",
    "Xã Bờ Ngoong",
    "Xã Canh Liên",
    "Xã Canh Vinh",
    "Xã Cát Tiến",
    "Xã Chơ Long",
    "Xã Chư A Thai",
    "Xã Chư Krey",
    "Xã Chư Păh",
    "Xã Chư Prông",
    "Xã Chư Pưh",
    "Xã Chư Sê",
    "Xã Cửu An",
    "Xã Đak Đoa",
    "Xã Đak Pơ",
    "Xã Đak Rong",
    "Xã Đak Sơmei",
    "Xã Đăk Song",
    "Xã Đề Gi",
    "Xã Đức Cơ",
    "Xã Gào",
    "Xã Hòa Hội",
    "Xã Hoài Ân",
    "Xã Hội Sơn",
    "Xã Hra",
    "Xã Ia Băng",
    "Xã Ia Boòng",
    "Xã Ia Chia",
    "Xã Ia Dơk",
    "Xã Ia Dom",
    "Xã Ia Dreh",
    "Xã Ia Grai",
    "Xã Ia Hiao",
    "Xã Ia Hrú",
    "Xã Ia Hrung",
    "Xã Ia Khươl",
    "Xã Ia Ko",
    "Xã Ia Krái",
    "Xã Ia Krêl",
    "Xã Ia Lâu",
    "Xã Ia Le",
    "Xã Ia Ly",
    "Xã Ia Mơ",
    "Xã Ia Nan",
    "Xã Ia O",
    "Xã Ia Pa",
    "Xã Ia Phí",
    "Xã Ia Pia",
    "Xã Ia Pnôn",
    "Xã Ia Púch",
    "Xã Ia Rbol",
    "Xã Ia Rsai",
    "Xã Ia Sao",
    "Xã Ia Tôr",
    "Xã Ia Tul",
    "Xã Kbang",
    "Xã KDang",
    "Xã Kim Sơn",
    "Xã Kon Chiêng",
    "Xã Kon Gang",
    "Xã Kông Bơ La",
    "Xã Kông Chro",
    "Xã Krong",
    "Xã Lơ Pang",
    "Xã Mang Yang",
    "Xã Ngô Mây",
    "Xã Nhơn Châu",
    "Xã Phù Cát",
    "Xã Phù Mỹ",
    "Xã Phù Mỹ Bắc",
    "Xã Phù Mỹ Đông",
    "Xã Phù Mỹ Nam",
    "Xã Phù Mỹ Tây",
    "Xã Phú Thiện",
    "Xã Phú Túc",
    "Xã Pờ Tó",
    "Xã Sơn Lang",
    "Xã SRó",
    "Xã Tây Sơn",
    "Xã Tơ Tung",
    "Xã Tuy Phước",
    "Xã Tuy Phước Bắc",
    "Xã Tuy Phước Đông",
    "Xã Tuy Phước Tây",
    "Xã Uar",
    "Xã Vân Canh",
    "Xã Vạn Đức",
    "Xã Vĩnh Quang",
    "Xã Vĩnh Sơn",
    "Xã Vĩnh Thạnh",
    "Xã Vĩnh Thịnh",
    "Xã Xuân An",
    "Xã Ya Hội",
    "Xã Ya Ma",
  ],
  "Tỉnh Hà Tĩnh": [
    "Phường Bắc Hồng Lĩnh",
    "Phường Hà Huy Tập",
    "Phường Hải Ninh",
    "Phường Hoành Sơn",
    "Phường Nam Hồng Lĩnh",
    "Phường Sông Trí",
    "Phường Thành Sen",
    "Phường Trần Phú",
    "Phường Vũng Áng",
    "Xã Cẩm Bình",
    "Xã Cẩm Duệ",
    "Xã Cẩm Hưng",
    "Xã Cẩm Lạc",
    "Xã Cẩm Trung",
    "Xã Cẩm Xuyên",
    "Xã Can Lộc",
    "Xã Cổ Đạm",
    "Xã Đan Hải",
    "Xã Đông Kinh",
    "Xã Đồng Lộc",
    "Xã Đồng Tiến",
    "Xã Đức Đồng",
    "Xã Đức Minh",
    "Xã Đức Quang",
    "Xã Đức Thịnh",
    "Xã Đức Thọ",
    "Xã Gia Hanh",
    "Xã Hà Linh",
    "Xã Hồng Lộc",
    "Xã Hương Bình",
    "Xã Hương Đô",
    "Xã Hương Khê",
    "Xã Hương Phố",
    "Xã Hương Sơn",
    "Xã Hương Xuân",
    "Xã Kim Hoa",
    "Xã Kỳ Anh",
    "Xã Kỳ Hoa",
    "Xã Kỳ Khang",
    "Xã Kỳ Lạc",
    "Xã Kỳ Thượng",
    "Xã Kỳ Văn",
    "Xã Kỳ Xuân",
    "Xã Lộc Hà",
    "Xã Mai Hoa",
    "Xã Mai Phụ",
    "Xã Nghi Xuân",
    "Xã Phúc Trạch",
    "Xã Sơn Giang",
    "Xã Sơn Hồng",
    "Xã Sơn Kim 1",
    "Xã Sơn Kim 2",
    "Xã Sơn Tây",
    "Xã Sơn Tiến",
    "Xã Thạch Hà",
    "Xã Thạch Khê",
    "Xã Thạch Lạc",
    "Xã Thạch Xuân",
    "Xã Thiên Cầm",
    "Xã Thượng Đức",
    "Xã Tiên Điền",
    "Xã Toàn Lưu",
    "Xã Trường Lưu",
    "Xã Tứ Mỹ",
    "Xã Tùng Lộc",
    "Xã Việt Xuyên",
    "Xã Vũ Quang",
    "Xã Xuân Lộc",
    "Xã Yên Hòa",
  ],
  "Tỉnh Hưng Yên": [
    "Phường Đường Hào",
    "Phường Hồng Châu",
    "Phường Mỹ Hào",
    "Phường Phố Hiến",
    "Phường Sơn Nam",
    "Phường Thái Bình",
    "Phường Thượng Hồng",
    "Phường Trà Lý",
    "Phường Trần Hưng Đạo",
    "Phường Trần Lãm",
    "Phường Vũ Phúc",
    "Xã  Bắc Đông Quan",
    "Xã A Sào",
    "Xã Ái Quốc",
    "Xã Ân Thi",
    "Xã Bắc Đông Hưng",
    "Xã Bắc Thái Ninh",
    "Xã Bắc Thụy Anh",
    "Xã Bắc Tiên Hưng",
    "Xã Bình Định",
    "Xã Bình Nguyên",
    "Xã Bình Thanh",
    "Xã Châu Ninh",
    "Xã Chí Minh",
    "Xã Đại Đồng",
    "Xã Diên Hà",
    "Xã Đoàn Đào",
    "Xã Đồng Bằng",
    "Xã Đồng Châu",
    "Xã Đông Hưng",
    "Xã Đông Quan",
    "Xã Đông Thái Ninh",
    "Xã Đông Thụy Anh",
    "Xã Đông Tiền Hải",
    "Xã Đông Tiên Hưng",
    "Xã Đức Hợp",
    "Xã Hiệp Cường",
    "Xã Hoàn Long",
    "Xã Hoàng Hoa Thám",
    "Xã Hồng Minh",
    "Xã Hồng Quang",
    "Xã Hồng Vũ",
    "Xã Hưng Hà",
    "Xã Hưng Phú",
    "Xã Khoái Châu",
    "Xã Kiến Xương",
    "Xã Lạc Đạo",
    "Xã Lê Lợi",
    "Xã Lê Quý Đôn",
    "Xã Long Hưng",
    "Xã Lương Bằng",
    "Xã Mễ Sở",
    "Xã Minh Thọ",
    "Xã Nam Cường",
    "Xã Nam Đông Hưng",
    "Xã Nam Thái Ninh",
    "Xã Nam Thụy Anh",
    "Xã Nam Tiền Hải",
    "Xã Nam Tiên Hưng",
    "Xã Nghĩa Dân",
    "Xã Nghĩa Trụ",
    "Xã Ngọc Lâm",
    "Xã Ngự Thiên",
    "Xã Nguyễn Du",
    "Xã Nguyễn Trãi",
    "Xã Nguyễn Văn Linh",
    "Xã Như Quỳnh",
    "Xã Phạm Ngũ Lão",
    "Xã Phụ Dực",
    "Xã Phụng Công",
    "Xã Quang Hưng",
    "Xã Quang Lịch",
    "Xã Quỳnh An",
    "Xã Quỳnh Phụ",
    "Xã Tân Hưng",
    "Xã Tân Thuận",
    "Xã Tân Tiến",
    "Xã Tây Thái Ninh",
    "Xã Tây Thụy Anh",
    "Xã Tây Tiền Hải",
    "Xã Thái Ninh",
    "Xã Thái Thụy",
    "Xã Thần Khê",
    "Xã Thư Trì",
    "Xã Thư Vũ",
    "Xã Thụy Anh",
    "Xã Tiền Hải",
    "Xã Tiên Hoa",
    "Xã Tiên Hưng",
    "Xã Tiên La",
    "Xã Tiên Lữ",
    "Xã Tiên Tiến",
    "Xã Tống Trân",
    "Xã Trà Giang",
    "Xã Triệu Việt Vương",
    "Xã Văn Giang",
    "Xã Vạn Xuân",
    "Xã Việt Tiến",
    "Xã Việt Yên",
    "Xã Vũ Quý",
    "Xã Vũ Thư",
    "Xã Vũ Tiên",
    "Xã Xuân Trúc",
    "Xã Yên Mỹ",
  ],
  "Tỉnh Khánh Hòa": [
    "Đặc khu Trường Sa",
    "Phường Ba Ngòi",
    "Phường Bắc Cam Ranh",
    "Phường Bắc Nha Trang",
    "Phường Bảo An",
    "Phường Cam Linh",
    "Phường Cam Ranh",
    "Phường Đô Vinh",
    "Phường Đông Hải",
    "Phường Đông Ninh Hòa",
    "Phường Hòa Thắng",
    "Phường Nam Nha Trang",
    "Phường Nha Trang",
    "Phường Ninh Chử",
    "Phường Ninh Hòa",
    "Phường Phan Rang",
    "Phường Tây Nha Trang",
    "Xã Anh Dũng",
    "Xã Bác Ái",
    "Xã Bác Ái Đông",
    "Xã Bác Ái Tây",
    "Xã Bắc Khánh Vĩnh",
    "Xã Bắc Ninh Hòa",
    "Xã Cà Ná",
    "Xã Cam An",
    "Xã Cam Hiệp",
    "Xã Cam Lâm",
    "Xã Công Hải",
    "Xã Đại Lãnh",
    "Xã Diên Điền",
    "Xã Diên Khánh",
    "Xã Diên Lạc",
    "Xã Diên Lâm",
    "Xã Diên Thọ",
    "Xã Đông Khánh Sơn",
    "Xã Hòa Trí",
    "Xã Khánh Sơn",
    "Xã Khánh Vĩnh",
    "Xã Lâm Sơn",
    "Xã Mỹ Sơn",
    "Xã Nam Cam Ranh",
    "Xã Nam Khánh Vĩnh",
    "Xã Nam Ninh Hòa",
    "Xã Ninh Hải",
    "Xã Ninh Phước",
    "Xã Ninh Sơn",
    "Xã Phước Dinh",
    "Xã Phước Hà",
    "Xã Phước Hậu",
    "Xã Phước Hữu",
    "Xã Suối Dầu",
    "Xã Suối Hiệp",
    "Xã Tân Định",
    "Xã Tây Khánh Sơn",
    "Xã Tây Khánh Vĩnh",
    "Xã Tây Ninh Hòa",
    "Xã Thuận Bắc",
    "Xã Thuận Nam",
    "Xã Trung Khánh Vĩnh",
    "Xã Tu Bông",
    "Xã Vạn Hưng",
    "Xã Vạn Ninh",
    "Xã Vạn Thắng",
    "Xã Vĩnh Hải",
    "Xã Xuân Hải",
  ],
  "Tỉnh Lai Châu": [
    "Phường Đoàn Kết",
    "Phường Tân Phong",
    "Xã Bản Bo",
    "Xã Bình Lư",
    "Xã Bum Nưa",
    "Xã Bum Tở",
    "Xã Dào San",
    "Xã Hồng Thu",
    "Xã Hua Bum",
    "Xã Khoen On",
    "Xã Khổng Lào",
    "Xã Khun Há",
    "Xã Lê Lợi",
    "Xã Mù Cả",
    "Xã Mường Khoa",
    "Xã Mường Kim",
    "Xã Mường Mô",
    "Xã Mường Tè",
    "Xã Mường Than",
    "Xã Nậm Cuổi",
    "Xã Nậm Hàng",
    "Xã Nậm Mạ",
    "Xã Nậm Sỏ",
    "Xã Nậm Tăm",
    "Xã Pa Tần",
    "Xã Pa Ủ",
    "Xã Pắc Ta",
    "Xã Phong Thổ",
    "Xã Pu Sam Cáp",
    "Xã Sì Lở Lầu",
    "Xã Sìn Hồ",
    "Xã Sin Suối Hồ",
    "Xã Tả Lèng",
    "Xã Tà Tổng",
    "Xã Tân Uyên",
    "Xã Than Uyên",
    "Xã Thu Lũm",
    "Xã Tủa Sín Chải",
  ],
  "Tỉnh Lâm Đồng": [
    "Đặc khu Phú Quý",
    "Phường 1 Bảo Lộc",
    "Phường 2 Bảo Lộc",
    "Phường 3 Bảo Lộc",
    "Phường B''Lao'",
    "Phường Bắc Gia Nghĩa",
    "Phường Bình Thuận",
    "Phường Cam Ly - Đà Lạt",
    "Phường Đông Gia Nghĩa",
    "Phường Hàm Thắng",
    "Phường La Gi",
    "Phường Lâm Viên - Đà Lạt",
    "Phường Lang Biang - Đà Lạt",
    "Phường Mũi Né",
    "Phường Nam Gia Nghĩa",
    "Phường Phan Thiết",
    "Phường Phú Thủy",
    "Phường Phước Hội",
    "Phường Tiến Thành",
    "Phường Xuân Hương - Đà Lạt",
    "Phường Xuân Trường - Đà Lạt",
    "Xã Bắc Bình",
    "Xã Bắc Ruộng",
    "Xã Bảo Lâm 1",
    "Xã Bảo Lâm 2",
    "Xã Bảo Lâm 3",
    "Xã Bảo Lâm 4",
    "Xã Bảo Lâm 5",
    "Xã Bảo Thuận",
    "Xã Cát Tiên",
    "Xã Cát Tiên 2",
    "Xã Cát Tiên 3",
    "Xã Cư Jút",
    "Xã D''Ran'",
    "Xã Đạ Huoai",
    "Xã Đạ Huoai 2",
    "Xã Đạ Huoai 3",
    "Xã Đạ Tẻh",
    "Xã Đạ Tẻh 2",
    "Xã Đạ Tẻh 3",
    "Xã Đắk Mil",
    "Xã Đắk Sắk",
    "Xã Đắk Song",
    "Xã Đắk Wil",
    "Xã Đam Rông 1",
    "Xã Đam Rông 2",
    "Xã Đam Rông 3",
    "Xã Đam Rông 4",
    "Xã Di Linh",
    "Xã Đinh Trang Thượng",
    "Xã Đinh Văn Lâm Hà",
    "Xã Đơn Dương",
    "Xã Đông Giang",
    "Xã Đồng Kho",
    "Xã Đức An",
    "Xã Đức Lập",
    "Xã Đức Linh",
    "Xã Đức Trọng",
    "Xã Gia Hiệp",
    "Xã Hải Ninh",
    "Xã Hàm Kiệm",
    "Xã Hàm Liêm",
    "Xã Hàm Tân",
    "Xã Hàm Thạnh",
    "Xã Hàm Thuận",
    "Xã Hàm Thuận Bắc",
    "Xã Hàm Thuận Nam",
    "Xã Hiệp Thạnh",
    "Xã Hòa Bắc",
    "Xã Hòa Ninh",
    "Xã Hòa Thắng",
    "Xã Hoài Đức",
    "Xã Hồng Sơn",
    "Xã Hồng Thái",
    "Xã Ka Đô",
    "Xã Kiến Đức",
    "Xã Krông Nô",
    "Xã La Dạ",
    "Xã Lạc Dương",
    "Xã Liên Hương",
    "Xã Lương Sơn",
    "Xã Nam Ban Lâm Hà",
    "Xã Nam Đà",
    "Xã Nam Dong",
    "Xã Nam Hà Lâm Hà",
    "Xã Nâm Nung",
    "Xã Nam Thành",
    "Xã Nghị Đức",
    "Xã Nhân Cơ",
    "Xã Ninh Gia",
    "Xã Phan Rí Cửa",
    "Xã Phan Sơn",
    "Xã Phú Sơn Lâm Hà",
    "Xã Phúc Thọ Lâm Hà",
    "Xã Quảng Hòa",
    "Xã Quảng Khê",
    "Xã Quảng Lập",
    "Xã Quảng Phú",
    "Xã Quảng Sơn",
    "Xã Quảng Tân",
    "Xã Quảng Tín",
    "Xã Quảng Trực",
    "Xã Sơn Điền",
    "Xã Sơn Mỹ",
    "Xã Sông Lũy",
    "Xã Suối Kiết",
    "Xã Tà Đùng",
    "Xã Tà Hine",
    "Xã Tà Năng",
    "Xã Tân Hà Lâm Hà",
    "Xã Tân Hải",
    "Xã Tân Hội",
    "Xã Tân Lập",
    "Xã Tân Minh",
    "Xã Tân Thành",
    "Xã Tánh Linh",
    "Xã Thuận An",
    "Xã Thuận Hạnh",
    "Xã Trà Tân",
    "Xã Trường Xuân",
    "Xã Tuy Đức",
    "Xã Tuy Phong",
    "Xã Tuyên Quang",
    "Xã Vĩnh Hảo",
  ],
  "Tỉnh Lạng Sơn": [
    "Phường Đông Kinh",
    "Phường Kỳ Lừa",
    "Phường Lương Văn Tri",
    "Phường Tam Thanh",
    "Xã Ba Sơn",
    "Xã Bắc Sơn",
    "Xã Bằng Mạc",
    "Xã Bình Gia",
    "Xã Cai Kinh",
    "Xã Cao Lộc",
    "Xã Châu Sơn",
    "Xã Chi Lăng",
    "Xã Chiến Thắng",
    "Xã Công Sơn",
    "Xã Điềm He",
    "Xã Đình Lập",
    "Xã Đoàn Kết",
    "Xã Đồng Đăng",
    "Xã Hoa Thám",
    "Xã Hoàng Văn Thụ",
    "Xã Hội Hoan",
    "Xã Hồng Phong",
    "Xã Hưng Vũ",
    "Xã Hữu Liên",
    "Xã Hữu Lũng",
    "Xã Kháng Chiến",
    "Xã Khánh Khê",
    "Xã Khuất Xá",
    "Xã Kiên Mộc",
    "Xã Lộc Bình",
    "Xã Lợi Bác",
    "Xã Mẫu Sơn",
    "Xã Na Dương",
    "Xã Na Sầm",
    "Xã Nhân Lý",
    "Xã Nhất Hòa",
    "Xã Quan Sơn",
    "Xã Quốc Khánh",
    "Xã Quốc Việt",
    "Xã Quý Hòa",
    "Xã Tân Đoàn",
    "Xã Tân Thành",
    "Xã Tân Tiến",
    "Xã Tân Tri",
    "Xã Tân Văn",
    "Xã Thái Bình",
    "Xã Thất Khê",
    "Xã Thiện Hòa",
    "Xã Thiện Long",
    "Xã Thiện Tân",
    "Xã Thiện Thuật",
    "Xã Thống Nhất",
    "Xã Thụy Hùng",
    "Xã Tràng Định",
    "Xã Tri Lễ",
    "Xã Tuấn Sơn",
    "Xã Văn Lãng",
    "Xã Vạn Linh",
    "Xã Vân Nham",
    "Xã Văn Quan",
    "Xã Vũ Lăng",
    "Xã Vũ Lễ",
    "Xã Xuân Dương",
    "Xã Yên Bình",
    "Xã Yên Phúc",
  ],
  "Tỉnh Lào Cai": [
    "Phường Âu Lâu",
    "Phường Cam Đường",
    "Phường Cầu Thia",
    "Phường Lào Cai",
    "Phường Nam Cường",
    "Phường Nghĩa Lộ",
    "Phường Sa Pa",
    "Phường Trung Tâm",
    "Phường Văn Phú",
    "Phường Yên Bái",
    "Xã A Mú Sung",
    "Xã Bắc Hà",
    "Xã Bản Hồ",
    "Xã Bản Lầu",
    "Xã Bản Liền",
    "Xã Bản Xèo",
    "Xã Bảo Ái",
    "Xã Bảo Hà",
    "Xã Bảo Nhai",
    "Xã Bảo Thắng",
    "Xã Bảo Yên",
    "Xã Bát Xát",
    "Xã Cảm Nhân",
    "Xã Cao Sơn",
    "Xã Cát Thịnh",
    "Xã Chấn Thịnh",
    "Xã Châu Quế",
    "Xã Chế Tạo",
    "Xã Chiềng Ken",
    "Xã Cốc Lầu",
    "Xã Cốc San",
    "Xã Dền Sáng",
    "Xã Đông Cuông",
    "Xã Dương Quỳ",
    "Xã Gia Hội",
    "Xã Gia Phú",
    "Xã Hạnh Phúc",
    "Xã Hợp Thành",
    "Xã Hưng Khánh",
    "Xã Khánh Hòa",
    "Xã Khánh Yên",
    "Xã Khao Mang",
    "Xã Lâm Giang",
    "Xã Lâm Thượng",
    "Xã Lao Chải",
    "Xã Liên Sơn",
    "Xã Lục Yên",
    "Xã Lùng Phình",
    "Xã Lương Thịnh",
    "Xã Mậu A",
    "Xã Minh Lương",
    "Xã Mỏ Vàng",
    "Xã Mù Cang Chải",
    "Xã Mường Bo",
    "Xã Mường Hum",
    "Xã Mường Khương",
    "Xã Mường Lai",
    "Xã Nậm Chày",
    "Xã Nậm Có",
    "Xã Nậm Xé",
    "Xã Nghĩa Đô",
    "Xã Nghĩa Tâm",
    "Xã Ngũ Chỉ Sơn",
    "Xã Pha Long",
    "Xã Phình Hồ",
    "Xã Phong Dụ Hạ",
    "Xã Phong Dụ Thượng",
    "Xã Phong Hải",
    "Xã Phúc Khánh",
    "Xã Phúc Lợi",
    "Xã Púng Luông",
    "Xã Quy Mông",
    "Xã Si Ma Cai",
    "Xã Sín Chéng",
    "Xã Sơn Lương",
    "Xã Tả Củ Tỷ",
    "Xã Tả Phìn",
    "Xã Tả Van",
    "Xã Tà Xi Láng",
    "Xã Tân Hợp",
    "Xã Tân Lĩnh",
    "Xã Tằng Loỏng",
    "Xã Thác Bà",
    "Xã Thượng Bằng La",
    "Xã Thượng Hà",
    "Xã Trạm Tấu",
    "Xã Trấn Yên",
    "Xã Trịnh Tường",
    "Xã Tú Lệ",
    "Xã Văn Bàn",
    "Xã Văn Chấn",
    "Xã Việt Hồng",
    "Xã Võ Lao",
    "Xã Xuân Ái",
    "Xã Xuân Hòa",
    "Xã Xuân Quang",
    "Xã Y Tý",
    "Xã Yên Bình",
    "Xã Yên Thành",
  ],
  "Tỉnh Nghệ An": [
    "Phường Cửa Lò",
    "Phường Hoàng Mai",
    "Phường Quỳnh Mai",
    "Phường Tân Mai",
    "Phường Tây Hiếu",
    "Phường Thái Hòa",
    "Phường Thành Vinh",
    "Phường Trường Vinh",
    "Phường Vinh Hưng",
    "Phường Vinh Lộc",
    "Phường Vinh Phú",
    "Xã An Châu",
    "Xã Anh Sơn",
    "Xã Anh Sơn Đông",
    "Xã Bắc Lý",
    "Xã Bạch Hà",
    "Xã Bạch Ngọc",
    "Xã Bích Hào",
    "Xã Bình Chuẩn",
    "Xã Bình Minh",
    "Xã Cam Phục",
    "Xã Cát Ngạn",
    "Xã Châu Bình",
    "Xã Châu Hồng",
    "Xã Châu Khê",
    "Xã Châu Lộc",
    "Xã Châu Tiến",
    "Xã Chiêu Lưu",
    "Xã Con Cuông",
    "Xã Đại Đồng",
    "Xã Đại Huệ",
    "Xã Diễn Châu",
    "Xã Đô Lương",
    "Xã Đông Hiếu",
    "Xã Đông Lộc",
    "Xã Đông Thành",
    "Xã Đức Châu",
    "Xã Giai Lạc",
    "Xã Giai Xuân",
    "Xã Hải Châu",
    "Xã Hải Lộc",
    "Xã Hạnh Lâm",
    "Xã Hoa Quân",
    "Xã Hợp Minh",
    "Xã Hùng Chân",
    "Xã Hùng Châu",
    "Xã Hưng Nguyên",
    "Xã Hưng Nguyên Nam",
    "Xã Huồi Tụ",
    "Xã Hữu Khuông",
    "Xã Hữu Kiệm",
    "Xã Keng Đu",
    "Xã Kim Bảng",
    "Xã Kim Liên",
    "Xã Lam Thành",
    "Xã Lượng Minh",
    "Xã Lương Sơn",
    "Xã Mậu Thạch",
    "Xã Minh Châu",
    "Xã Minh Hợp",
    "Xã Môn Sơn",
    "Xã Mường Chọng",
    "Xã Mường Ham",
    "Xã Mường Lống",
    "Xã Mường Quàng",
    "Xã Mường Típ",
    "Xã Mường Xén",
    "Xã Mỹ Lý",
    "Xã Na Loi",
    "Xã Na Ngoi",
    "Xã Nậm Cắn",
    "Xã Nam Đàn",
    "Xã Nga My",
    "Xã Nghi Lộc",
    "Xã Nghĩa Đàn",
    "Xã Nghĩa Đồng",
    "Xã Nghĩa Hành",
    "Xã Nghĩa Hưng",
    "Xã Nghĩa Khánh",
    "Xã Nghĩa Lâm",
    "Xã Nghĩa Lộc",
    "Xã Nghĩa Mai",
    "Xã Nghĩa Thọ",
    "Xã Nhân Hòa",
    "Xã Nhôn Mai",
    "Xã Phúc Lộc",
    "Xã Quan Thành",
    "Xã Quảng Châu",
    "Xã Quang Đồng",
    "Xã Quế Phong",
    "Xã Quỳ Châu",
    "Xã Quỳ Hợp",
    "Xã Quỳnh Anh",
    "Xã Quỳnh Lưu",
    "Xã Quỳnh Phú",
    "Xã Quỳnh Sơn",
    "Xã Quỳnh Tam",
    "Xã Quỳnh Thắng",
    "Xã Quỳnh Văn",
    "Xã Sơn Lâm",
    "Xã Tam Đồng",
    "Xã Tam Hợp",
    "Xã Tam Quang",
    "Xã Tam Thái",
    "Xã Tân An",
    "Xã Tân Châu",
    "Xã Tân Kỳ",
    "Xã Tân Phú",
    "Xã Thần Lĩnh",
    "Xã Thành Bình Thọ",
    "Xã Thiên Nhẫn",
    "Xã Thông Thụ",
    "Xã Thuần Trung",
    "Xã Tiên Đồng",
    "Xã Tiền Phong",
    "Xã Tri Lễ",
    "Xã Trung Lộc",
    "Xã Tương Dương",
    "Xã Vạn An",
    "Xã Vân Du",
    "Xã Văn Hiến",
    "Xã Văn Kiều",
    "Xã Vân Tụ",
    "Xã Vĩnh Tường",
    "Xã Xuân Lâm",
    "Xã Yên Hòa",
    "Xã Yên Na",
    "Xã Yên Thành",
    "Xã Yên Trung",
    "Xã Yên Xuân",
  ],
  "Tỉnh Ninh Bình": [
    "Phường Châu Sơn",
    "Phường Đông A",
    "Phường Đông Hoa Lư",
    "Phường Đồng Văn",
    "Phường Duy Hà",
    "Phường Duy Tân",
    "Phường Duy Tiên",
    "Phường Hà Nam",
    "Phường Hoa Lư",
    "Phường Hồng Quang",
    "Phường Kim Bảng",
    "Phường Kim Thanh",
    "Phường Lê Hồ",
    "Phường Liêm Tuyền",
    "Phường Lý Thường Kiệt",
    "Phường Mỹ Lộc",
    "Phường Nam Định",
    "Phường Nam Hoa Lư",
    "Phường Nguyễn Úy",
    "Phường Phủ Lý",
    "Phường Phù Vân",
    "Phường Tam Chúc",
    "Phường Tam Điệp",
    "Phường Tây Hoa Lư",
    "Phường Thành Nam",
    "Phường Thiên Trường",
    "Phường Tiên Sơn",
    "Phường Trung Sơn",
    "Phường Trường Thi",
    "Phường Vị Khê",
    "Phường Yên Sơn",
    "Phường Yên Thắng",
    "Xã Bắc Lý",
    "Xã Bình An",
    "Xã Bình Giang",
    "Xã Bình Lục",
    "Xã Bình Minh",
    "Xã Bình Mỹ",
    "Xã Bình Sơn",
    "Xã Cát Thành",
    "Xã Chất Bình",
    "Xã Cổ Lễ",
    "Xã Cúc Phương",
    "Xã Đại Hoàng",
    "Xã Định Hóa",
    "Xã Đồng Thái",
    "Xã Đồng Thịnh",
    "Xã Gia Hưng",
    "Xã Gia Lâm",
    "Xã Gia Phong",
    "Xã Gia Trấn",
    "Xã Gia Tường",
    "Xã Gia Vân",
    "Xã Gia Viễn",
    "Xã Giao Bình",
    "Xã Giao Hòa",
    "Xã Giao Hưng",
    "Xã Giao Minh",
    "Xã Giao Ninh",
    "Xã Giao Phúc",
    "Xã Giao Thủy",
    "Xã Hải An",
    "Xã Hải Anh",
    "Xã Hải Hậu",
    "Xã Hải Hưng",
    "Xã Hải Quang",
    "Xã Hải Thịnh",
    "Xã Hải Tiến",
    "Xã Hải Xuân",
    "Xã Hiển Khánh",
    "Xã Hồng Phong",
    "Xã Khánh Hội",
    "Xã Khánh Nhạc",
    "Xã Khánh Thiện",
    "Xã Khánh Trung",
    "Xã Kim Đông",
    "Xã Kim Sơn",
    "Xã Lai Thành",
    "Xã Liêm Hà",
    "Xã Liên Minh",
    "Xã Lý Nhân",
    "Xã Minh Tân",
    "Xã Minh Thái",
    "Xã Nam Đồng",
    "Xã Nam Hồng",
    "Xã Nam Lý",
    "Xã Nam Minh",
    "Xã Nam Ninh",
    "Xã Nam Trực",
    "Xã Nam Xang",
    "Xã Nghĩa Hưng",
    "Xã Nghĩa Lâm",
    "Xã Nghĩa Sơn",
    "Xã Nhân Hà",
    "Xã Nho Quan",
    "Xã Ninh Cường",
    "Xã Ninh Giang",
    "Xã Phát Diệm",
    "Xã Phong Doanh",
    "Xã Phú Long",
    "Xã Phú Sơn",
    "Xã Quang Hưng",
    "Xã Quang Thiện",
    "Xã Quỹ Nhất",
    "Xã Quỳnh Lưu",
    "Xã Rạng Đông",
    "Xã Tân Minh",
    "Xã Tân Thanh",
    "Xã Thanh Bình",
    "Xã Thanh Lâm",
    "Xã Thanh Liêm",
    "Xã Thanh Sơn",
    "Xã Trần Thương",
    "Xã Trực Ninh",
    "Xã Vạn Thắng",
    "Xã Vĩnh Trụ",
    "Xã Vụ Bản",
    "Xã Vũ Dương",
    "Xã Xuân Giang",
    "Xã Xuân Hồng",
    "Xã Xuân Hưng",
    "Xã Xuân Trường",
    "Xã Ý Yên",
    "Xã Yên Cường",
    "Xã Yên Đồng",
    "Xã Yên Khánh",
    "Xã Yên Mạc",
    "Xã Yên Mô",
    "Xã Yên Từ",
  ],
  "Tỉnh Phú Thọ": [
    "Phường Âu Cơ",
    "Phường Hòa Bình",
    "Phường Kỳ Sơn",
    "Phường Nông Trang",
    "Phường Phong Châu",
    "Phường Phú Thọ",
    "Phường Phúc Yên",
    "Phường Tân Hòa",
    "Phường Thanh Miếu",
    "Phường Thống Nhất",
    "Phường Vân Phú",
    "Phường Việt Trì",
    "Phường Vĩnh Phúc",
    "Phường Vĩnh Yên",
    "Phường Xuân Hòa",
    "Xã An Bình",
    "Xã An Nghĩa",
    "Xã Bản Nguyên",
    "Xã Bằng Luân",
    "Xã Bao La",
    "Xã Bình Nguyên",
    "Xã Bình Phú",
    "Xã Bình Tuyền",
    "Xã Bình Xuyên",
    "Xã Cẩm Khê",
    "Xã Cao Dương",
    "Xã Cao Phong",
    "Xã Cao Sơn",
    "Xã Chân Mộng",
    "Xã Chí Đám",
    "Xã Chí Tiên",
    "Xã Cự Đồng",
    "Xã Đà Bắc",
    "Xã Đại Đình",
    "Xã Đại Đồng",
    "Xã Dân Chủ",
    "Xã Đan Thượng",
    "Xã Đạo Trù",
    "Xã Đào Xá",
    "Xã Đoan Hùng",
    "Xã Đồng Lương",
    "Xã Đông Thành",
    "Xã Đức Nhàn",
    "Xã Dũng Tiến",
    "Xã Hạ Hòa",
    "Xã Hải Lựu",
    "Xã Hiền Lương",
    "Xã Hiền Quan",
    "Xã Hoàng An",
    "Xã Hoàng Cương",
    "Xã Hội Thịnh",
    "Xã Hợp Kim",
    "Xã Hợp Lý",
    "Xã Hùng Việt",
    "Xã Hương Cần",
    "Xã Hy Cương",
    "Xã Khả Cửu",
    "Xã Kim Bôi",
    "Xã Lạc Lương",
    "Xã Lạc Sơn",
    "Xã Lạc Thủy",
    "Xã Lai Đồng",
    "Xã Lâm Thao",
    "Xã Lập Thạch",
    "Xã Liên Châu",
    "Xã Liên Hòa",
    "Xã Liên Minh",
    "Xã Liên Sơn",
    "Xã Long Cốc",
    "Xã Lương Sơn",
    "Xã Mai Châu",
    "Xã Mai Hạ",
    "Xã Minh Đài",
    "Xã Minh Hòa",
    "Xã Mường Bi",
    "Xã Mường Động",
    "Xã Mường Hoa",
    "Xã Mường Thàng",
    "Xã Mường Vang",
    "Xã Nật Sơn",
    "Xã Ngọc Sơn",
    "Xã Nguyệt Đức",
    "Xã Nhân Nghĩa",
    "Xã Pà Cò",
    "Xã Phú Khê",
    "Xã Phú Mỹ",
    "Xã Phù Ninh",
    "Xã Phùng Nguyên",
    "Xã Quảng Yên",
    "Xã Quy Đức",
    "Xã Quyết Thắng",
    "Xã Sơn Đông",
    "Xã Sơn Lương",
    "Xã Sông Lô",
    "Xã Tam Đảo",
    "Xã Tam Dương",
    "Xã Tam Dương Bắc",
    "Xã Tam Hồng",
    "Xã Tam Nông",
    "Xã Tam Sơn",
    "Xã Tân Lạc",
    "Xã Tân Mai",
    "Xã Tân Pheo",
    "Xã Tân Sơn",
    "Xã Tây Cốc",
    "Xã Tề Lỗ",
    "Xã Thái Hòa",
    "Xã Thanh Ba",
    "Xã Thanh Sơn",
    "Xã Thanh Thủy",
    "Xã Thịnh Minh",
    "Xã Thổ Tang",
    "Xã Thọ Văn",
    "Xã Thu Cúc",
    "Xã Thung Nai",
    "Xã Thượng Cốc",
    "Xã Thượng Long",
    "Xã Tiên Lữ",
    "Xã Tiên Lương",
    "Xã Tiền Phong",
    "Xã Toàn Thắng",
    "Xã Trạm Thản",
    "Xã Trung Sơn",
    "Xã Tu Vũ",
    "Xã Vân Bán",
    "Xã Văn Lang",
    "Xã Văn Miếu",
    "Xã Vân Sơn",
    "Xã Vạn Xuân",
    "Xã Vĩnh An",
    "Xã Vĩnh Chân",
    "Xã Vĩnh Hưng",
    "Xã Vĩnh Phú",
    "Xã Vĩnh Thành",
    "Xã Vĩnh Tường",
    "Xã Võ Miếu",
    "Xã Xuân Đài",
    "Xã Xuân Lãng",
    "Xã Xuân Lũng",
    "Xã Xuân Viên",
    "Xã Yên Kỳ",
    "Xã Yên Lạc",
    "Xã Yên Lãng",
    "Xã Yên Lập",
    "Xã Yên Phú",
    "Xã Yên Sơn",
    "Xã Yên Thủy",
    "Xã Yên Trị",
  ],
  "Tỉnh Quảng Ngãi": [
    "Đặc khu Lý Sơn",
    "Phường Cẩm Thành",
    "Phường Đăk Bla",
    "Phường Đăk Cấm",
    "Phường Đức Phổ",
    "Phường Kon Tum",
    "Phường Nghĩa Lộ",
    "Phường Sa Huỳnh",
    "Phường Trà Câu",
    "Phường Trương Quang Trọng",
    "Xã An Phú",
    "Xã Ba Dinh",
    "Xã Ba Động",
    "Xã Ba Gia",
    "Xã Ba Tô",
    "Xã Ba Tơ",
    "Xã Ba Vì",
    "Xã Ba Vinh",
    "Xã Ba Xa",
    "Xã Bình Chương",
    "Xã Bình Minh",
    "Xã Bình Sơn",
    "Xã Bờ Y",
    "Xã Cà Đam",
    "Xã Đăk Hà",
    "Xã Đăk Kôi",
    "Xã Đăk Long",
    "Xã Đăk Mar",
    "Xã Đăk Môn",
    "Xã Đăk Pék",
    "Xã Đăk Plô",
    "Xã Đăk Pxi",
    "Xã Đăk Rơ Wa",
    "Xã Đăk Rve",
    "Xã Đăk Sao",
    "Xã Đăk Tô",
    "Xã Đăk Tờ Kan",
    "Xã Đăk Ui",
    "Xã Đặng Thùy Trâm",
    "Xã Đình Cương",
    "Xã Đông Sơn",
    "Xã Đông Trà Bồng",
    "Xã Dục Nông",
    "Xã Ia Chim",
    "Xã Ia Đal",
    "Xã Ia Tơi",
    "Xã Khánh Cường",
    "Xã Kon Braih",
    "Xã Kon Đào",
    "Xã Kon Plông",
    "Xã Lân Phong",
    "Xã Long Phụng",
    "Xã Măng Bút",
    "Xã Măng Đen",
    "Xã Măng Ri",
    "Xã Minh Long",
    "Xã Mỏ Cày",
    "Xã Mộ Đức",
    "Xã Mô Rai",
    "Xã Nghĩa Giang",
    "Xã Nghĩa Hành",
    "Xã Ngọc Linh",
    "Xã Ngọk Bay",
    "Xã Ngọk Réo",
    "Xã Ngọk Tụ",
    "Xã Nguyễn Nghiêm",
    "Xã Phước Giang",
    "Xã Rờ Kơi",
    "Xã Sa Bình",
    "Xã Sa Loong",
    "Xã Sa Thầy",
    "Xã Sơn Hà",
    "Xã Sơn Hạ",
    "Xã Sơn Kỳ",
    "Xã Sơn Linh",
    "Xã Sơn Mai",
    "Xã Sơn Tây",
    "Xã Sơn Tây Hạ",
    "Xã Sơn Tây Thượng",
    "Xã Sơn Thủy",
    "Xã Sơn Tịnh",
    "Xã Tây Trà",
    "Xã Tây Trà Bồng",
    "Xã Thanh Bồng",
    "Xã Thiện Tín",
    "Xã Thọ Phong",
    "Xã Tịnh Khê",
    "Xã Trà Bồng",
    "Xã Trà Giang",
    "Xã Trường Giang",
    "Xã Tu Mơ Rông",
    "Xã Tư Nghĩa",
    "Xã Vạn Tường",
    "Xã Vệ Giang",
    "Xã Xốp",
    "Xã Ya Ly",
  ],
  "Tỉnh Quảng Ninh": [
    "Đặc khu Cô Tô",
    "Đặc khu Vân Đồn",
    "Phường An Sinh",
    "Phường Bãi Cháy",
    "Phường Bình Khê",
    "Phường Cẩm Phả",
    "Phường Cao Xanh",
    "Phường Cửa Ông",
    "Phường Đông Mai",
    "Phường Đông Triều",
    "Phường Hà An",
    "Phường Hà Lầm",
    "Phường Hạ Long",
    "Phường Hà Tu",
    "Phường Hiệp Hòa",
    "Phường Hoàng Quế",
    "Phường Hoành Bồ",
    "Phường Hồng Gai",
    "Phường Liên Hòa",
    "Phường Mạo Khê",
    "Phường Móng Cái 1",
    "Phường Móng Cái 2",
    "Phường Móng Cái 3",
    "Phường Mông Dương",
    "Phường Phong Cốc",
    "Phường Quang Hanh",
    "Phường Quảng Yên",
    "Phường Tuần Châu",
    "Phường Uông Bí",
    "Phường Vàng Danh",
    "Phường Việt Hưng",
    "Phường Yên Tử",
    "Xã Ba Chẽ",
    "Xã Bình Liêu",
    "Xã Cái Chiên",
    "Xã Đầm Hà",
    "Xã Điền Xá",
    "Xã Đông Ngũ",
    "Xã Đường Hoa",
    "Xã Hải Hòa",
    "Xã Hải Lạng",
    "Xã Hải Ninh",
    "Xã Hải Sơn",
    "Xã Hoành Mô",
    "Xã Kỳ Thượng",
    "Xã Lục Hồn",
    "Xã Lương Minh",
    "Xã Quảng Đức",
    "Xã Quảng Hà",
    "Xã Quảng La",
    "Xã Quảng Tân",
    "Xã Thống Nhất",
    "Xã Tiên Yên",
    "Xã Vĩnh Thực",
  ],
  "Tỉnh Quảng Trị": [
    "Đặc khu Cồn Cỏ",
    "Phường Ba Đồn",
    "Phường Bắc Gianh",
    "Phường Đông Hà",
    "Phường Đồng Hới",
    "Phường Đồng Sơn",
    "Phường Đồng Thuận",
    "Phường Nam Đông Hà",
    "Phường Quảng Trị",
    "Xã A Dơi",
    "Xã Ái Tử",
    "Xã Ba Lòng",
    "Xã Bắc Trạch",
    "Xã Bến Hải",
    "Xã Bến Quan",
    "Xã Bố Trạch",
    "Xã Cam Hồng",
    "Xã Cam Lộ",
    "Xã Cồn Tiên",
    "Xã Cửa Tùng",
    "Xã Cửa Việt",
    "Xã Đakrông",
    "Xã Dân Hóa",
    "Xã Diên Sanh",
    "Xã Đồng Lê",
    "Xã Đông Trạch",
    "Xã Gio Linh",
    "Xã Hải Lăng",
    "Xã Hiếu Giang",
    "Xã Hòa Trạch",
    "Xã Hoàn Lão",
    "Xã Hướng Hiệp",
    "Xã Hướng Lập",
    "Xã Hướng Phùng",
    "Xã Khe Sanh",
    "Xã Kim Điền",
    "Xã Kim Ngân",
    "Xã Kim Phú",
    "Xã La Lay",
    "Xã Lao Bảo",
    "Xã Lệ Ninh",
    "Xã Lệ Thủy",
    "Xã Lìa",
    "Xã Minh Hóa",
    "Xã Mỹ Thủy",
    "Xã Nam Ba Đồn",
    "Xã Nam Cửa Việt",
    "Xã Nam Gianh",
    "Xã Nam Hải Lăng",
    "Xã Nam Trạch",
    "Xã Ninh Châu",
    "Xã Phong Nha",
    "Xã Phú Trạch",
    "Xã Quảng Ninh",
    "Xã Quảng Trạch",
    "Xã Sen Ngư",
    "Xã Tà Rụt",
    "Xã Tân Gianh",
    "Xã Tân Lập",
    "Xã Tân Mỹ",
    "Xã Tân Thành",
    "Xã Thượng Trạch",
    "Xã Triệu Bình",
    "Xã Triệu Cơ",
    "Xã Triệu Phong",
    "Xã Trung Thuần",
    "Xã Trường Ninh",
    "Xã Trường Phú",
    "Xã Trường Sơn",
    "Xã Tuyên Bình",
    "Xã Tuyên Hóa",
    "Xã Tuyên Lâm",
    "Xã Tuyên Phú",
    "Xã Tuyên Sơn",
    "Xã Vĩnh Định",
    "Xã Vĩnh Hoàng",
    "Xã Vĩnh Linh",
    "Xã Vĩnh Thủy",
  ],
  "Tỉnh Sơn La": [
    "Phường Chiềng An",
    "Phường Chiềng Cơi",
    "Phường Chiềng Sinh",
    "Phường Mộc Châu",
    "Phường Mộc Sơn",
    "Phường Thảo Nguyên",
    "Phường Tô Hiệu",
    "Phường Vân Sơn",
    "Xã Bắc Yên",
    "Xã Bình Thuận",
    "Xã Bó Sinh",
    "Xã Chiềng Hặc",
    "Xã Chiềng Hoa",
    "Xã Chiềng Khoong",
    "Xã Chiềng Khương",
    "Xã Chiềng La",
    "Xã Chiềng Lao",
    "Xã Chiềng Mai",
    "Xã Chiềng Mung",
    "Xã Chiềng Sại",
    "Xã Chiềng Sơ",
    "Xã Chiềng Sơn",
    "Xã Chiềng Sung",
    "Xã Co Mạ",
    "Xã Đoàn Kết",
    "Xã Gia Phù",
    "Xã Huổi Một",
    "Xã Kim Bon",
    "Xã Long Hẹ",
    "Xã Lóng Phiêng",
    "Xã Lóng Sập",
    "Xã Mai Sơn",
    "Xã Muổi Nọi",
    "Xã Mường Bám",
    "Xã Mường Bang",
    "Xã Mường Bú",
    "Xã Mường Chanh",
    "Xã Mường Chiên",
    "Xã Mường Cơi",
    "Xã Mường É",
    "Xã Mường Giôn",
    "Xã Mường Hung",
    "Xã Mường Khiêng",
    "Xã Mường La",
    "Xã Mường Lầm",
    "Xã Mường Lạn",
    "Xã Mường Lèo",
    "Xã Mường Sại",
    "Xã Nậm Lầu",
    "Xã Nậm Ty",
    "Xã Ngọc Chiến",
    "Xã Pắc Ngà",
    "Xã Phiêng Cằm",
    "Xã Phiêng Khoài",
    "Xã Phiêng Pằn",
    "Xã Phù Yên",
    "Xã Púng Bánh",
    "Xã Quỳnh Nhai",
    "Xã Song Khủa",
    "Xã Sông Mã",
    "Xã Sốp Cộp",
    "Xã Suối Tọ",
    "Xã Tà Hộc",
    "Xã Tạ Khoa",
    "Xã Tà Xùa",
    "Xã Tân Phong",
    "Xã Tân Yên",
    "Xã Thuận Châu",
    "Xã Tô Múa",
    "Xã Tường Hạ",
    "Xã Vân Hồ",
    "Xã Xím Vàng",
    "Xã Xuân Nha",
    "Xã Yên Châu",
    "Xã Yên Sơn",
  ],
  "Tỉnh Tây Ninh": [
    "Phường An Tịnh",
    "Phường Bình Minh",
    "Phường Gia Lộc",
    "Phường Gò Dầu",
    "Phường Hòa Thành",
    "Phường Khánh Hậu",
    "Phường Kiến Tường",
    "Phường Long An",
    "Phường Long Hoa",
    "Phường Ninh Thạnh",
    "Phường Tân An",
    "Phường Tân Ninh",
    "Phường Thanh Điền",
    "Phường Trảng Bàng",
    "Xã An Lục Long",
    "Xã An Ninh",
    "Xã Bến Cầu",
    "Xã Bến Lức",
    "Xã Bình Đức",
    "Xã Bình Hiệp",
    "Xã Bình Hòa",
    "Xã Bình Thành",
    "Xã Cần Đước",
    "Xã Cần Giuộc",
    "Xã Cầu Khởi",
    "Xã Châu Thành",
    "Xã Đông Thành",
    "Xã Đức Hòa",
    "Xã Đức Huệ",
    "Xã Đức Lập",
    "Xã Dương Minh Châu",
    "Xã Hảo Đước",
    "Xã Hậu Nghĩa",
    "Xã Hậu Thạnh",
    "Xã Hiệp Hòa",
    "Xã Hòa Hội",
    "Xã Hòa Khánh",
    "Xã Hưng Điền",
    "Xã Hưng Thuận",
    "Xã Khánh Hưng",
    "Xã Lộc Ninh",
    "Xã Long Cang",
    "Xã Long Chữ",
    "Xã Long Hựu",
    "Xã Long Thuận",
    "Xã Lương Hòa",
    "Xã Mộc Hóa",
    "Xã Mỹ An",
    "Xã Mỹ Hạnh",
    "Xã Mỹ Lệ",
    "Xã Mỹ Lộc",
    "Xã Mỹ Quý",
    "Xã Mỹ Thạnh",
    "Xã Mỹ Yên",
    "Xã Nhơn Hòa Lập",
    "Xã Nhơn Ninh",
    "Xã Nhựt Tảo",
    "Xã Ninh Điền",
    "Xã Phước Chỉ",
    "Xã Phước Lý",
    "Xã Phước Thạnh",
    "Xã Phước Vinh",
    "Xã Phước Vĩnh Tây",
    "Xã Rạch Kiến",
    "Xã Tầm Vu",
    "Xã Tân Biên",
    "Xã Tân Châu",
    "Xã Tân Đông",
    "Xã Tân Hòa",
    "Xã Tân Hội",
    "Xã Tân Hưng",
    "Xã Tân Lân",
    "Xã Tân Lập",
    "Xã Tân Long",
    "Xã Tân Phú",
    "Xã Tân Tập",
    "Xã Tân Tây",
    "Xã Tân Thành",
    "Xã Tân Thạnh",
    "Xã Tân Trụ",
    "Xã Thạnh Bình",
    "Xã Thạnh Đức",
    "Xã Thạnh Hóa",
    "Xã Thạnh Lợi",
    "Xã Thạnh Phước",
    "Xã Thủ Thừa",
    "Xã Thuận Mỹ",
    "Xã Trà Vong",
    "Xã Truông Mít",
    "Xã Tuyên Bình",
    "Xã Tuyên Thạnh",
    "Xã Vàm Cỏ",
    "Xã Vĩnh Châu",
    "Xã Vĩnh Công",
    "Xã Vĩnh Hưng",
    "Xã Vĩnh Thạnh",
  ],
  "Tỉnh Thái Nguyên": [
    "Phường Bá Xuyên",
    "Phường Bắc Kạn",
    "Phường Bách Quang",
    "Phường Đức Xuân",
    "Phường Gia Sàng",
    "Phường Linh Sơn",
    "Phường Phan Đình Phùng",
    "Phường Phổ Yên",
    "Phường Phúc Thuận",
    "Phường Quan Triều",
    "Phường Quyết Thắng",
    "Phường Sông Công",
    "Phường Tích Lương",
    "Phường Trung Thành",
    "Phường Vạn Xuân",
    "Xã An Khánh",
    "Xã Ba Bể",
    "Xã Bạch Thông",
    "Xã Bằng Thành",
    "Xã Bằng Vân",
    "Xã Bình Thành",
    "Xã Bình Yên",
    "Xã Cẩm Giàng",
    "Xã Cao Minh",
    "Xã Chợ Đồn",
    "Xã Chợ Mới",
    "Xã Chợ Rã",
    "Xã Côn Minh",
    "Xã Cường Lợi",
    "Xã Đại Phúc",
    "Xã Đại Từ",
    "Xã Dân Tiến",
    "Xã Điềm Thụy",
    "Xã Định Hóa",
    "Xã Đồng Hỷ",
    "Xã Đồng Phúc",
    "Xã Đức Lương",
    "Xã Hiệp Lực",
    "Xã Hợp Thành",
    "Xã Kha Sơn",
    "Xã Kim Phượng",
    "Xã La Bằng",
    "Xã La Hiên",
    "Xã Lam Vỹ",
    "Xã Nà Phặc",
    "Xã Na Rì",
    "Xã Nam Cường",
    "Xã Nam Hòa",
    "Xã Ngân Sơn",
    "Xã Nghĩa Tá",
    "Xã Nghiên Loan",
    "Xã Nghinh Tường",
    "Xã Phong Quang",
    "Xã Phú Bình",
    "Xã Phú Đình",
    "Xã Phú Lạc",
    "Xã Phú Lương",
    "Xã Phú Thịnh",
    "Xã Phủ Thông",
    "Xã Phú Xuyên",
    "Xã Phúc Lộc",
    "Xã Phượng Tiến",
    "Xã Quân Chu",
    "Xã Quảng Bạch",
    "Xã Quang Sơn",
    "Xã Sảng Mộc",
    "Xã Tân Cương",
    "Xã Tân Khánh",
    "Xã Tân Kỳ",
    "Xã Tân Thành",
    "Xã Thần Sa",
    "Xã Thành Công",
    "Xã Thanh Mai",
    "Xã Thanh Thịnh",
    "Xã Thượng Minh",
    "Xã Thượng Quan",
    "Xã Trại Cau",
    "Xã Trần Phú",
    "Xã Tràng Xá",
    "Xã Trung Hội",
    "Xã Văn Hán",
    "Xã Văn Lang",
    "Xã Văn Lăng",
    "Xã Vạn Phú",
    "Xã Vĩnh Thông",
    "Xã Võ Nhai",
    "Xã Vô Tranh",
    "Xã Xuân Dương",
    "Xã Yên Bình",
    "Xã Yên Phong",
    "Xã Yên Thịnh",
    "Xã Yên Trạch",
  ],
  "Tỉnh Thanh Hóa": [
    "Phường Bỉm Sơn",
    "Phường Đào Duy Từ",
    "Phường Đông Quang",
    "Phường Đông Sơn",
    "Phường Đông Tiến",
    "Phường Hạc Thành",
    "Phường Hải Bình",
    "Phường Hải Lĩnh",
    "Phường Hàm Rồng",
    "Phường Nam Sầm Sơn",
    "Phường Nghi Sơn",
    "Phường Ngọc Sơn",
    "Phường Nguyệt Viên",
    "Phường Quảng Phú",
    "Phường Quang Trung",
    "Phường Sầm Sơn",
    "Phường Tân Dân",
    "Phường Tĩnh Gia",
    "Phường Trúc Lâm",
    "Xã An Nông",
    "Xã Ba Đình",
    "Xã Bá Thước",
    "Xã Bát Mọt",
    "Xã Biện Thượng",
    "Xã Các Sơn",
    "Xã Cẩm Tân",
    "Xã Cẩm Thạch",
    "Xã Cẩm Thủy",
    "Xã Cẩm Tú",
    "Xã Cẩm Vân",
    "Xã Cổ Lũng",
    "Xã Công Chính",
    "Xã Điền Lư",
    "Xã Điền Quang",
    "Xã Định Hòa",
    "Xã Định Tân",
    "Xã Đồng Lương",
    "Xã Đông Thành",
    "Xã Đồng Tiến",
    "Xã Giao An",
    "Xã Hà Long",
    "Xã Hà Trung",
    "Xã Hậu Lộc",
    "Xã Hiền Kiệt",
    "Xã Hồ Vương",
    "Xã Hoa Lộc",
    "Xã Hóa Quỳ",
    "Xã Hoằng Châu",
    "Xã Hoằng Giang",
    "Xã Hoằng Hóa",
    "Xã Hoằng Lộc",
    "Xã Hoằng Phú",
    "Xã Hoằng Sơn",
    "Xã Hoằng Thanh",
    "Xã Hoằng Tiến",
    "Xã Hoạt Giang",
    "Xã Hồi Xuân",
    "Xã Hợp Tiến",
    "Xã Kiên Thọ",
    "Xã Kim Tân",
    "Xã Lam Sơn",
    "Xã Linh Sơn",
    "Xã Lĩnh Toại",
    "Xã Luận Thành",
    "Xã Lương Sơn",
    "Xã Lưu Vệ",
    "Xã Mậu Lâm",
    "Xã Minh Sơn",
    "Xã Mường Chanh",
    "Xã Mường Lát",
    "Xã Mường Lý",
    "Xã Mường Mìn",
    "Xã Na Mèo",
    "Xã Nam Xuân",
    "Xã Nga An",
    "Xã Nga Sơn",
    "Xã Nga Thắng",
    "Xã Ngọc Lặc",
    "Xã Ngọc Liên",
    "Xã Ngọc Trạo",
    "Xã Nguyệt Ấn",
    "Xã Nhi Sơn",
    "Xã Như Thanh",
    "Xã Như Xuân",
    "Xã Nông Cống",
    "Xã Phú Lệ",
    "Xã Phú Xuân",
    "Xã Pù Luông",
    "Xã Pù Nhi",
    "Xã Quan Sơn",
    "Xã Quảng Bình",
    "Xã Quang Chiểu",
    "Xã Quảng Chính",
    "Xã Quảng Ngọc",
    "Xã Quảng Ninh",
    "Xã Quảng Yên",
    "Xã Quý Lộc",
    "Xã Quý Lương",
    "Xã Sao Vàng",
    "Xã Sơn Điện",
    "Xã Sơn Thủy",
    "Xã Tam Chung",
    "Xã Tam Lư",
    "Xã Tam Thanh",
    "Xã Tân Ninh",
    "Xã Tân Thành",
    "Xã Tân Tiến",
    "Xã Tây Đô",
    "Xã Thạch Bình",
    "Xã Thạch Lập",
    "Xã Thạch Quảng",
    "Xã Thăng Bình",
    "Xã Thắng Lộc",
    "Xã Thắng Lợi",
    "Xã Thanh Kỳ",
    "Xã Thanh Phong",
    "Xã Thanh Quân",
    "Xã Thành Vinh",
    "Xã Thiên Phủ",
    "Xã Thiết Ống",
    "Xã Thiệu Hóa",
    "Xã Thiệu Quang",
    "Xã Thiệu Tiến",
    "Xã Thiệu Toán",
    "Xã Thiệu Trung",
    "Xã Thọ Bình",
    "Xã Thọ Lập",
    "Xã Thọ Long",
    "Xã Thọ Ngọc",
    "Xã Thọ Phú",
    "Xã Thọ Xuân",
    "Xã Thượng Ninh",
    "Xã Thường Xuân",
    "Xã Tiên Trang",
    "Xã Tống Sơn",
    "Xã Triệu Lộc",
    "Xã Triệu Sơn",
    "Xã Trung Chính",
    "Xã Trung Hạ",
    "Xã Trung Lý",
    "Xã Trung Sơn",
    "Xã Trung Thành",
    "Xã Trường Lâm",
    "Xã Trường Văn",
    "Xã Tượng Lĩnh",
    "Xã Vân Du",
    "Xã Vạn Lộc",
    "Xã Văn Nho",
    "Xã Văn Phú",
    "Xã Vạn Xuân",
    "Xã Vĩnh Lộc",
    "Xã Xuân Bình",
    "Xã Xuân Chinh",
    "Xã Xuân Du",
    "Xã Xuân Hòa",
    "Xã Xuân Lập",
    "Xã Xuân Thái",
    "Xã Xuân Tín",
    "Xã Yên Định",
    "Xã Yên Khương",
    "Xã Yên Nhân",
    "Xã Yên Ninh",
    "Xã Yên Phú",
    "Xã Yên Thắng",
    "Xã Yên Thọ",
    "Xã Yên Trường",
  ],
  "Tỉnh Tuyên Quang": [
    "Phường An Tường",
    "Phường Bình Thuận",
    "Phường Hà Giang 1",
    "Phường Hà Giang 2",
    "Phường Minh Xuân",
    "Phường Mỹ Lâm",
    "Phường Nông Tiến",
    "Xã Bắc Mê",
    "Xã Bắc Quang",
    "Xã Bạch Đích",
    "Xã Bạch Ngọc",
    "Xã Bạch Xa",
    "Xã Bản Máy",
    "Xã Bằng Hành",
    "Xã Bằng Lang",
    "Xã Bình An",
    "Xã Bình Ca",
    "Xã Bình Xa",
    "Xã Cán Tỷ",
    "Xã Cao Bồ",
    "Xã Chiêm Hóa",
    "Xã Côn Lôn",
    "Xã Đồng Tâm",
    "Xã Đông Thọ",
    "Xã Đồng Văn",
    "Xã Đồng Yên",
    "Xã Du Già",
    "Xã Đường Hồng",
    "Xã Đường Thượng",
    "Xã Giáp Trung",
    "Xã Hàm Yên",
    "Xã Hồ Thầu",
    "Xã Hòa An",
    "Xã Hoàng Su Phì",
    "Xã Hồng Sơn",
    "Xã Hồng Thái",
    "Xã Hùng An",
    "Xã Hùng Đức",
    "Xã Hùng Lợi",
    "Xã Khâu Vai",
    "Xã Khuôn Lùng",
    "Xã Kiên Đài",
    "Xã Kiến Thiết",
    "Xã Kim Bình",
    "Xã Lâm Bình",
    "Xã Lao Chải",
    "Xã Liên Hiệp",
    "Xã Linh Hồ",
    "Xã Lực Hành",
    "Xã Lũng Cú",
    "Xã Lũng Phìn",
    "Xã Lùng Tám",
    "Xã Mậu Duệ",
    "Xã Mèo Vạc",
    "Xã Minh Ngọc",
    "Xã Minh Quang",
    "Xã Minh Sơn",
    "Xã Minh Tân",
    "Xã Minh Thanh",
    "Xã Nà Hang",
    "Xã Nấm Dẩn",
    "Xã Nậm Dịch",
    "Xã Nghĩa Thuận",
    "Xã Ngọc Đường",
    "Xã Ngọc Long",
    "Xã Nhữ Khê",
    "Xã Niêm Sơn",
    "Xã Pà Vầy Sủ",
    "Xã Phố Bảng",
    "Xã Phú Linh",
    "Xã Phú Lương",
    "Xã Phù Lưu",
    "Xã Pờ Ly Ngài",
    "Xã Quản Bạ",
    "Xã Quang Bình",
    "Xã Quảng Nguyên",
    "Xã Sà Phìn",
    "Xã Sơn Dương",
    "Xã Sơn Thủy",
    "Xã Sơn Vĩ",
    "Xã Sủng Máng",
    "Xã Tân An",
    "Xã Tân Long",
    "Xã Tân Mỹ",
    "Xã Tân Quang",
    "Xã Tân Thanh",
    "Xã Tân Tiến",
    "Xã Tân Trào",
    "Xã Tân Trịnh",
    "Xã Tát Ngà",
    "Xã Thái Bình",
    "Xã Thái Hòa",
    "Xã Thái Sơn",
    "Xã Thắng Mố",
    "Xã Thàng Tín",
    "Xã Thanh Thủy",
    "Xã Thông Nguyên",
    "Xã Thuận Hòa",
    "Xã Thượng Lâm",
    "Xã Thượng Nông",
    "Xã Thượng Sơn",
    "Xã Tiên Nguyên",
    "Xã Tiên Yên",
    "Xã Tri Phú",
    "Xã Trung Hà",
    "Xã Trung Sơn",
    "Xã Trung Thịnh",
    "Xã Trường Sinh",
    "Xã Tùng Bá",
    "Xã Tùng Vài",
    "Xã Vị Xuyên",
    "Xã Việt Lâm",
    "Xã Vĩnh Tuy",
    "Xã Xín Mần",
    "Xã Xuân Giang",
    "Xã Xuân Vân",
    "Xã Yên Cường",
    "Xã Yên Hoa",
    "Xã Yên Lập",
    "Xã Yên Minh",
    "Xã Yên Nguyên",
    "Xã Yên Phú",
    "Xã Yên Sơn",
    "Xã Yên Thành",
  ],
  "Tỉnh Vĩnh Long": [
    "Phường An Hội",
    "Phường Bến Tre",
    "Phường Bình Minh",
    "Phường Cái Vồn",
    "Phường Đông Thành",
    "Phường Duyên Hải",
    "Phường Hòa Thuận",
    "Phường Long Châu",
    "Phường Long Đức",
    "Phường Nguyệt Hóa",
    "Phường Phú Khương",
    "Phường Phú Tân",
    "Phường Phước Hậu",
    "Phường Sơn Đông",
    "Phường Tân Hạnh",
    "Phường Tân Ngãi",
    "Phường Thanh Đức",
    "Phường Trà Vinh",
    "Phường Trường Long Hòa",
    "Xã An Bình",
    "Xã An Định",
    "Xã An Hiệp",
    "Xã An Ngãi Trung",
    "Xã An Phú Tân",
    "Xã An Qui",
    "Xã An Trường",
    "Xã Ba Tri",
    "Xã Bảo Thạnh",
    "Xã Bình Đại",
    "Xã Bình Phú",
    "Xã Bình Phước",
    "Xã Cái Ngang",
    "Xã Cái Nhum",
    "Xã Càng Long",
    "Xã Cầu Kè",
    "Xã Cầu Ngang",
    "Xã Châu Hòa",
    "Xã Châu Hưng",
    "Xã Châu Thành",
    "Xã Chợ Lách",
    "Xã Đại An",
    "Xã Đại Điền",
    "Xã Đôn Châu",
    "Xã Đông Hải",
    "Xã Đồng Khởi",
    "Xã Giao Long",
    "Xã Giồng Trôm",
    "Xã Hàm Giang",
    "Xã Hiệp Mỹ",
    "Xã Hiếu Phụng",
    "Xã Hiếu Thành",
    "Xã Hòa Bình",
    "Xã Hòa Hiệp",
    "Xã Hòa Minh",
    "Xã Hùng Hòa",
    "Xã Hưng Khánh Trung",
    "Xã Hưng Mỹ",
    "Xã Hưng Nhượng",
    "Xã Hương Mỹ",
    "Xã Lộc Thuận",
    "Xã Long Hiệp",
    "Xã Long Hồ",
    "Xã Long Hòa",
    "Xã Long Hữu",
    "Xã Long Thành",
    "Xã Long Vĩnh",
    "Xã Lục Sĩ Thành",
    "Xã Lương Hòa",
    "Xã Lương Phú",
    "Xã Lưu Nghiệp Anh",
    "Xã Mỏ Cày",
    "Xã Mỹ Chánh Hòa",
    "Xã Mỹ Long",
    "Xã Mỹ Thuận",
    "Xã Ngãi Tứ",
    "Xã Ngũ Lạc",
    "Xã Nhị Long",
    "Xã Nhị Trường",
    "Xã Nhơn Phú",
    "Xã Nhuận Phú Tân",
    "Xã Phong Thạnh",
    "Xã Phú Phụng",
    "Xã Phú Quới",
    "Xã Phú Thuận",
    "Xã Phú Túc",
    "Xã Phước Long",
    "Xã Phước Mỹ Trung",
    "Xã Quới An",
    "Xã Quới Điền",
    "Xã Quới Thiện",
    "Xã Song Lộc",
    "Xã Song Phú",
    "Xã Tam Bình",
    "Xã Tam Ngãi",
    "Xã Tân An",
    "Xã Tân Hào",
    "Xã Tân Hòa",
    "Xã Tân Long Hội",
    "Xã Tân Lược",
    "Xã Tân Phú",
    "Xã Tân Quới",
    "Xã Tân Thành Bình",
    "Xã Tân Thủy",
    "Xã Tân Xuân",
    "Xã Tập Ngãi",
    "Xã Tập Sơn",
    "Xã Thạnh Hải",
    "Xã Thạnh Phong",
    "Xã Thạnh Phú",
    "Xã Thạnh Phước",
    "Xã Thành Thới",
    "Xã Thạnh Trị",
    "Xã Thới Thuận",
    "Xã Tiên Thủy",
    "Xã Tiểu Cần",
    "Xã Trà Côn",
    "Xã Trà Cú",
    "Xã Trà Ôn",
    "Xã Trung Hiệp",
    "Xã Trung Ngãi",
    "Xã Trung Thành",
    "Xã Vinh Kim",
    "Xã Vĩnh Thành",
    "Xã Vĩnh Xuân",
  ],
} as const;
